"""PULSE Paediatrics — hand-crafted CLINICAL CASE (vignette) bank.
Inserted at the end of the target unit by audit.py. `ans` is authoritive;
audit.py rotates the option position. Options are deliberately same-category
and similar length so the answer cannot be spotted by length or type.
"""

CASES = [
    # ---------------- CH1 · Normal Newborn (p2-6) ----------------
    {"ch": 1, "unit": "PEDS-U013",
     "stem": "A term male is delivered by vacuum extraction. Within 2 hours he has a diffuse, fluctuant swelling of the scalp that crosses suture lines. He is pale, tachycardic (182/min) and his capillary refill is 4 seconds.",
     "q": "The most likely diagnosis is —",
     "opts": ["Subgaleal hemorrhage", "Caput succedaneum", "Cephalohematoma", "Occipital encephalocele"],
     "ans": 0, "exp": "Vacuum extraction → separation of scalp layers below galea aponeurotica → blood accumulation; diffuse, fluctuant, crosses sutures, appears soon after birth, most severe (shock, pallor). (Book p6)"},
    {"ch": 1, "unit": "PEDS-U001",
     "stem": "A baby boy is born at 34 weeks of gestation with a birth weight of 1.4 kg. He is active and feeding well. His mother wants to know how his weight will be categorised.",
     "q": "This baby's birth weight is best classified as —",
     "opts": ["Very low birth weight", "Low birth weight", "Extremely low birth weight", "Normal birth weight"],
     "ans": 0, "exp": "VLBW = birth weight < 1.5 kg; this baby (1.4 kg) is VLBW (and also LBW since < 2.5 kg, but not ELBW which is < 1 kg). (Book p2)"},
    {"ch": 1, "unit": "PEDS-U009",
     "stem": "At 1 minute of life a term baby has: heart rate 110/min, slow irregular breathing, some flexion of extremities, a grimace with weak cry when the nasal mucosa is irritated with a nasogastric tube, and a pink trunk with blue extremities.",
     "q": "The 1-minute APGAR score of this baby is —",
     "opts": ["6/10", "8/10", "4/10", "10/10"],
     "ans": 0, "exp": "Pulse >100 = 2; irregular breathing = 1; some flexion = 1; grimace with weak cry = 1; acrocyanosis = 1 → total 6/10 (low; moderate asphyxia range 4-6). (Book p4)"},
    {"ch": 1, "unit": "PEDS-U011",
     "stem": "A well, full-term breastfed baby develops scattered papules and pustules on the trunk and face on day 3 of life. He is afebrile and feeds normally. Lesion smear shows abundant eosinophils.",
     "q": "The most likely diagnosis is —",
     "opts": ["Erythema toxicum neonatorum", "Transient neonatal pustular melanosis", "Epithelial inclusion cysts", "Neonatal herpes simplex"],
     "ans": 0, "exp": "Erythema toxicum: papulopustular lesions, eosinophils on smear, onset > 24 hr, baby otherwise well. (Pustular melanosis: neutrophils, onset < 24 hr.) (Book p5)"},

    # ---------------- CH2 · Neonatal Resuscitation (p7-10) ----------------
    {"ch": 2, "unit": "PEDS-U023",
     "stem": "A term baby receives 30 seconds of effective bag-and-mask ventilation after initial steps. The heart rate is now checked and is 50/min.",
     "q": "The next step in management is —",
     "opts": ["Start chest compressions", "Give IV adrenaline first", "Continue PPV for 60 more seconds", "Stop resuscitation efforts"],
     "ans": 0, "exp": "After effective PPV, HR < 60/min → start chest compressions (3:1 with ventilation); adrenaline if HR remains < 60. (Book p10)"},
    {"ch": 2, "unit": "PEDS-U021",
     "stem": "During bag-and-mask ventilation of a newborn, no chest rise is seen and there is no heart rate improvement.",
     "q": "The FIRST corrective step (MRSOPA) is —",
     "opts": ["Mask adjustment", "Suction the mouth and nose", "Increase ventilation pressure", "Insert an alternative airway"],
     "ans": 0, "exp": "MRSOPA: M — Mask adjustment first, then R — Reposition airway, S — Suction, O — Open mouth, P — Pressure increase, A — Alternative airway. (Book p9)"},
    {"ch": 2, "unit": "PEDS-U023",
     "stem": "A newborn continues to have a heart rate of 48/min despite 60 seconds of coordinated chest compressions and ventilation. The umbilical vein is accessible.",
     "q": "Adrenaline should be given —",
     "opts": ["IV via the umbilical vein", "Endotracheal tube route", "Intraosseous route", "Intramuscular into the thigh"],
     "ans": 0, "exp": "Preferred route: IV through the umbilical vein (1:10,000, 0.1 mL/kg); intraosseous only if IV inaccessible. (Book p10)"},
    {"ch": 2, "unit": "PEDS-U020",
     "stem": "A newborn at term does not cry after birth. After warming, drying and positioning the airway, he is still apnoeic and gasping.",
     "q": "The next step is —",
     "opts": ["Bag-and-mask ventilation", "Oxygen hood supplementation", "Nasal prong oxygen", "Chest compressions"],
     "ans": 0, "exp": "Apnoea/gasping after initial steps → PPV by bag-and-mask (non-invasive first choice) at 40-60/min. (Book p8)"},

    # ---------------- CH3 · NEC and Neonatal Sepsis (p11-15) ----------------
    {"ch": 3, "unit": "PEDS-U024",
     "stem": "A 12-day-old preterm (29 weeks) infant, on enteral feeds, develops increasing abdominal distension, feed intolerance and blood-tinged stools. Abdominal X-ray shows pneumatosis intestinalis and portal venous gas.",
     "q": "The most likely diagnosis is —",
     "opts": ["Necrotizing enterocolitis", "Hirschsprung enterocolitis", "Neonatal sepsis with ileus", "Malrotation with volvulus"],
     "ans": 0, "exp": "Preterm + feed intolerance + distension + PR bleeding + pneumatosis intestinalis = NEC. (Book p11)"},
    {"ch": 3, "unit": "PEDS-U025",
     "stem": "The baby described above (distension, PR bleeding, pneumatosis intestinalis) also has metabolic acidosis and mild systemic toxicity but is hemodynamically stable.",
     "q": "The Modified Bell stage is —",
     "opts": ["Stage IIb", "Stage Ia", "Stage IIIa", "Stage IIa"],
     "ans": 0, "exp": "Definite NEC (pneumatosis) + acidosis/moderately ill = Bell stage IIb; III implies severe illness/shock/perforation. (Book p11-12)"},
    {"ch": 3, "unit": "PEDS-U026",
     "stem": "A preterm baby with NEC (Bell stage IIa) is hemodynamically stable. The surgical team has been informed.",
     "q": "Initial management consists of —",
     "opts": ["Nil per oral with IV antibiotics", "Immediate laparotomy", "Continuing enteral feeds", "Oral antibiotics alone"],
     "ans": 0, "exp": "Medical management until stage IIIb: NPO, orogastric decompression, IV fluids/TPN, IV antibiotics (gram+, gram−, anaerobe cover). (Book p12)"},
    {"ch": 3, "unit": "PEDS-U027",
     "stem": "A term baby whose mother had rupture of membranes for 26 hours develops poor feeding, lethargy and respiratory distress at 18 hours of life.",
     "q": "This presentation is classified as —",
     "opts": ["Early onset neonatal sepsis", "Late onset neonatal sepsis", "Necrotizing enterocolitis", "Congenital TORCH infection"],
     "ans": 0, "exp": "Early onset sepsis: within 72 hours (book ≤ 3 days), often with maternal risk factors (PROM, chorioamnionitis); presents as respiratory distress. (Book p13)"},

    # ---------------- CH4 · Respiratory Distress (p16-20) ----------------
    {"ch": 4, "unit": "PEDS-U036",
     "stem": "A term baby is born by elective lower-segment caesarean section. At 1 hour he has tachypnoea (RR 78/min) with mild retractions, but pink saturations and good feeding. Chest X-ray shows perihilar streaking and fluid in the fissures.",
     "q": "The most likely diagnosis is —",
     "opts": ["Transient tachypnea of newborn", "Respiratory distress syndrome", "Meconium aspiration syndrome", "Neonatal pneumonia"],
     "ans": 0, "exp": "TTNB: term/LSCS baby, early tachypnoea, mild distress, X-ray perihilar streaks + fluid in fissures; resolves in 24-48 hr (m/c overall cause of early respiratory distress). (Book p17)"},
    {"ch": 4, "unit": "PEDS-U038",
     "stem": "A 30-week preterm baby develops grunting, nasal flaring and severe retractions at 4 hours of life. Chest X-ray shows a ground-glass appearance with air bronchograms.",
     "q": "The specific therapy indicated is —",
     "opts": ["Exogenous surfactant via ETT", "IV antibiotics alone", "Furosemide infusion", "Chest physiotherapy"],
     "ans": 0, "exp": "RDS (hyaline membrane disease): preterm, surfactant deficiency, ground-glass X-ray → exogenous surfactant replacement via endotracheal route. (Book p18)"},
    {"ch": 4, "unit": "PEDS-U039",
     "stem": "A post-term baby is born through thick meconium-stained liquor. He cries at birth but by 6 hours has tachypnoea and coarse, patchy infiltrates on chest X-ray with hyperinflation.",
     "q": "The most likely diagnosis is —",
     "opts": ["Meconium aspiration syndrome", "Transient tachypnea of newborn", "Respiratory distress syndrome", "Spontaneous pneumothorax"],
     "ans": 0, "exp": "MAS: meconium-stained liquor + respiratory distress + coarse infiltrates with hyperinflation on X-ray (inactivated surfactant → impaired gas exchange). (Book p19)"},
    {"ch": 4, "unit": "PEDS-U040",
     "stem": "A newborn has severe respiratory distress with a scaphoid abdomen, absent breath sounds and bowel sounds in the left hemithorax, and the heart displaced to the right.",
     "q": "The immediate management is —",
     "opts": ["Endotracheal intubation and ventilation", "Bag-and-mask ventilation", "Immediate surgical repair", "Nasal CPAP"],
     "ans": 0, "exp": "CDH: mechanical ventilation via endotracheal tube (up lung expansion); bag-and-mask ventilation is avoided (worsens bowel distension inside chest); surgery only after stabilisation. (Book p20)"},

    # ---------------- CH5 · Neonatal Jaundice (p21-24) ----------------
    {"ch": 5, "unit": "PEDS-U043",
     "stem": "A term baby develops jaundice on day 3, limited to the face and chest (Kramer zone 2). Total serum bilirubin is 9 mg/dL, predominantly unconjugated. He feeds well and is clinically normal.",
     "q": "The most likely diagnosis is —",
     "opts": ["Physiological jaundice", "ABO haemolytic disease", "Breast milk jaundice", "Biliary atresia"],
     "ans": 0, "exp": "Physiological jaundice: appears after 24 hr (day 2-3), unconjugated, peaks 5-7 mg/dL (term), baby well, resolves 1-2 weeks. (Book p22)"},
    {"ch": 5, "unit": "PEDS-U044",
     "stem": "A 3-week-old infant has persistent jaundice with pale clay-coloured stools and dark yellow urine. Total bilirubin is 8 mg/dL with direct (conjugated) fraction 4.2 mg/dL. Abdominal examination is unremarkable.",
     "q": "The most likely diagnosis is —",
     "opts": ["Biliary atresia", "Physiological jaundice", "Breast milk jaundice", "G6PD deficiency haemolysis"],
     "ans": 0, "exp": "Conjugated hyperbilirubinaemia (> 2 mg/dL or > 20%) + pale stools + dark urine beyond 2 weeks = biliary atresia (obstructive/direct jaundice). (Book p22)"},
    {"ch": 5, "unit": "PEDS-U046",
     "stem": "A well term baby on day 3 has a total serum bilirubin of 16 mg/dL, which plots above the phototherapy line for his age on the normogram. There are no signs of acute bilirubin encephalopathy.",
     "q": "The next step in management is —",
     "opts": ["Intensive phototherapy", "Exchange transfusion", "Recheck bilirubin after 48 hours", "Stop breastfeeding"],
     "ans": 0, "exp": "TSB above the phototherapy-threshold line on the age-specific normogram → intensive phototherapy; exchange transfusion is for failure of phototherapy or encephalopathy signs. (Book p23-24)"},
    {"ch": 5, "unit": "PEDS-U045",
     "stem": "A 16-day-old exclusively breastfed term baby is well and gaining weight normally. Jaundice persists with an unconjugated bilirubin of 11 mg/dL; stools are normally coloured and urine is pale.",
     "q": "The most likely cause is —",
     "opts": ["Breast milk jaundice", "Breastfeeding (starvation) jaundice", "ABO incompatibility", "Congenital hypothyroidism"],
     "ans": 0, "exp": "Breast milk jaundice: well baby, prolonged unconjugated jaundice (1st-2nd week, may last weeks), normal stools, good weight gain; continue breastfeeding. (Book p23)"},

    # ---------------- CH6 · Hypothermia & Hypoglycemia (p25-29) ----------------
    {"ch": 6, "unit": "PEDS-U051",
     "stem": "A 2-day-old stable preterm baby's axillary temperature is recorded as 34.8°C. The baby is breathing normally, is pink and feeds by cup and spoon.",
     "q": "The most appropriate method of rewarming is —",
     "opts": ["Kangaroo mother care with a cap", "Rapid warm-water bath", "Leaving the baby unwrapped", "Antipyretic therapy"],
     "ans": 0, "exp": "Stable baby: KMC (skin-to-skin) + cover head to toe with cap (moderate hypothermia 32-36°C). Warmer/incubator is for the unstable baby. (Book p25)"},
    {"ch": 6, "unit": "PEDS-U054",
     "stem": "A 6-hour-old infant of a diabetic mother becomes jittery and then has a brief generalized seizure. Capillary glucose is 26 mg/dL.",
     "q": "The immediate management is —",
     "opts": ["IV 10% dextrose 2 mL/kg bolus", "Oral 10% dextrose alone", "IM glucagon injection", "Continue observation for 1 hour"],
     "ans": 0, "exp": "Symptomatic hypoglycemia (< 45 mg/dL with seizures): IV dextrose 2 mL/kg of 10% dextrose bolus, then glucose infusion (GIR 6-8 mg/kg/min). (Book p27)"},
    {"ch": 6, "unit": "PEDS-U055",
     "stem": "A 3-week-old macrosomic infant has persistent hypoglycemia (requiring > 12 mg/kg/min glucose) with inappropriately high insulin. Diet and dextrose infusion are already optimized.",
     "q": "The drug used to decrease insulin production is —",
     "opts": ["Diazoxide", "Hydrocortisone", "Glucagon", "Adrenaline"],
     "ans": 0, "exp": "Resistant hypoglycemia: to ↓ insulin production use diazoxide, octreotide; hydrocortisone/glucagon instead stimulate gluconeogenesis. (Avoid diazoxide/glucagon in SGA.) (Book p28)"},
    {"ch": 6, "unit": "PEDS-U056",
     "stem": "An infant of a type-1 diabetic mother is born large-for-gestational age at 38 weeks and develops grunting and retractions soon after birth, along with hypoglycemia and polycythaemia.",
     "q": "The respiratory distress in this baby is attributed to —",
     "opts": ["Hyperinsulinemia delaying surfactant maturation", "Aspiration of gastric contents", "Neonatal pneumonia", "Congenital diaphragmatic hernia"],
     "ans": 0, "exp": "IDM (Pedersen hypothesis: maternal glucose → fetal hyperinsulinism): LGA, hypoglycemia, polycythaemia and RDS (hyperinsulinemia delays surfactant maturation); also ASH, lazy colon. (Book p28-29)"},

    # ---------------- CH7 · Reflexes, HIE & Seizures (p30-34) ----------------
    {"ch": 7, "unit": "PEDS-U058",
     "stem": "A newborn after shoulder dystocia holds his right arm adducted and internally rotated. The right-sided Moro response is absent while the left is normal.",
     "q": "The most likely cause of the asymmetric Moro is —",
     "opts": ["Erb's palsy (C5-C6)", "Klumpke's palsy (C8-T1)", "Congenital myopathy", "Hemispheric brain infarct"],
     "ans": 0, "exp": "Asymmetric/absent Moro on one side with the classic 'waiter's tip' posture = brachial plexus injury, upper roots C5-C6 (Erb's palsy). (Book p30)"},
    {"ch": 7, "unit": "PEDS-U061",
     "stem": "A term baby with perinatal asphyxia is lethargic on day 1 with hypotonia, weak suck and seizures; Moro and grasp reflexes are depressed. By day 3 he is more alert and the seizures have stopped.",
     "q": "The Sarnat stage of this baby is —",
     "opts": ["Stage II (moderate HIE)", "Stage I (mild HIE)", "Stage III (severe HIE)", "No encephalopathy"],
     "ans": 0, "exp": "Sarnat stage II: lethargy, hypotonia, seizures (day 1-2) with depressed primitive reflexes, improving by end of first week. (Book p32)"},
    {"ch": 7, "unit": "PEDS-U063",
     "stem": "A 4-hour-old term baby has moderate HIE (Sarnat stage II) after a difficult delivery. The hospital has a cooling facility.",
     "q": "The best neuroprotective intervention is —",
     "opts": ["Whole-body therapeutic hypothermia", "Selective head cooling", "Prophylactic phenobarbitone", "Hyperbaric oxygen therapy"],
     "ans": 0, "exp": "Therapeutic hypothermia (33.5-34.5°C) within 6 hours, ≤ 72 hours, for stage 2/3 HIE ≥ 36 weeks; whole-body cooling is the better method. (Book p33-34)"},
    {"ch": 7, "unit": "PEDS-U065",
     "stem": "A term baby with birth asphyxia develops subtle seizures (lip smacking, eye deviation, bicycling movements) at 18 hours of life. Glucose and calcium are normal.",
     "q": "The first-line antiepileptic is —",
     "opts": ["IV Phenobarbitone", "IV Phenytoin", "Midazolam infusion", "Pyridoxine"],
     "ans": 0, "exp": "Neonatal seizures (m/c cause: HIE): first line IV phenobarbitone → phenytoin/levetiracetam → midazolam infusion; pyridoxine trial if refractory. (Book p34)"},

    # ---------------- CH8 · Normal Growth (p35-40) ----------------
    {"ch": 8, "unit": "PEDS-U070",
     "stem": "A baby whose birth weight was 3 kg is brought for a routine visit. At 6 months he weighs 6.2 kg and follows the 50th percentile on the growth chart. He is exclusively breastfed and developmentally normal.",
     "q": "This weight pattern is —",
     "opts": ["Normal — weight doubles by 5-6 months", "Failure to thrive", "Severe acute malnutrition", "Overnutrition"],
     "ans": 0, "exp": "Birth weight doubles by 5-6 months, triples by 1 year, quadruples by 2 years; this baby (6.2 kg at 6 months) is tracking normally. (Book p37)"},
    {"ch": 8, "unit": "PEDS-U073",
     "stem": "A 16-month-old girl is screened at an anganwadi centre. Her mid-arm circumference (MUAC) measures 11.0 cm. She has no pedal oedema and is alert.",
     "q": "The MUAC finding classifies her as —",
     "opts": ["Severe acute malnutrition", "Moderate acute malnutrition", "Normal nutrition", "Overweight"],
     "ans": 0, "exp": "MUAC (Shakir's tape): < 11.5 cm = severe malnutrition (red); 11.5-12.5 cm = moderate (yellow); > 12.5 cm = normal. (Book p39)"},
    {"ch": 8, "unit": "PEDS-U067",
     "stem": "A 12-year-old girl has just attained menarche. Her mother asks about the sequence of events of female puberty that has already occurred.",
     "q": "The correct sequence in girls is —",
     "opts": ["Thelarche → pubarche → growth spurt → menarche", "Pubarche → thelarche → menarche → growth spurt", "Growth spurt → thelarche → menarche → pubarche", "Thelarche → menarche → pubarche → growth spurt"],
     "ans": 0, "exp": "Female sequence: thelarche (breast bud) → pubarche → growth spurt → menarche. (In boys: testicular enlargement → pubarche → growth spurt.) (Book p35)"},
    {"ch": 8, "unit": "PEDS-U075",
     "stem": "A 4-year-old's weight has fallen from the 50th to just below the 3rd percentile over 12 months. She has recurrent infections and a poor appetite. Parents are of average height.",
     "q": "This pattern indicates —",
     "opts": ["Abnormal growth velocity — needs evaluation", "Normal catch-down growth", "Familial short stature", "Constitutional delay of growth"],
     "ans": 0, "exp": "Crossing two or more major centile lines downward = abnormal growth velocity → evaluate (in this child: pathological cause). Catch-down is a normal variant without symptoms. (Book p40)"},

    # ---------------- CH9 · Head Size & Shape (p41-44) ----------------
    {"ch": 9, "unit": "PEDS-U077",
     "stem": "A 2-year-old has microcephaly, severe intellectual disability, fair skin and hair, eczema, and a mousy odour of the urine. Plasma phenylalanine is markedly elevated.",
     "q": "The underlying enzyme deficiency is —",
     "opts": ["Phenylalanine hydroxylase", "Cystathionine β-synthase", "Hexosaminidase A", "Galactose-1-phosphate uridyltransferase"],
     "ans": 0, "exp": "PKU: phenylalanine hydroxylase deficiency → microcephaly, intellectual disability, mousy urine odour, fair skin (also a secondary (treatable) microcephaly). (Book p41)"},
    {"ch": 9, "unit": "PEDS-U078",
     "stem": "A baby with microcephaly, short palpebral fissures, smooth philtrum, thin upper lip and a ventricular septal defect is born to a mother with chronic alcohol use.",
     "q": "The most likely diagnosis is —",
     "opts": ["Fetal alcohol syndrome", "Fetal hydantoin syndrome", "Congenital rubella syndrome", "Cornelia de Lange syndrome"],
     "ans": 0, "exp": "FAS (teratogen-related microcephaly): short palpebral fissures, smooth/long philtrum, thin upper lip, cardiac defects + microcephaly. (Book p42)"},
    {"ch": 9, "unit": "PEDS-U081",
     "stem": "A 1-year-old has an enlarging head with hepatosplenomegaly, developmental regression and a cherry-red macular spot.",
     "q": "This macrocephaly is due to —",
     "opts": ["Megalencephaly from a lysosomal storage disease", "Ventriculomegaly with raised ICT", "Thick skull from a bone disorder", "Chronic subdural haemorrhage"],
     "ans": 0, "exp": "Megalencephaly (↑ brain volume): metabolic causes = lysosomal storage diseases (Sandhoff with HSM + cherry-red spot; Tay-Sachs without HSM) and genetic causes. (Book p43)"},
    {"ch": 9, "unit": "PEDS-U084",
     "stem": "A child has craniosynostosis with midface hypoplasia, proptosis and a beaked nose. His hands and feet are completely normal.",
     "q": "The most likely syndrome is —",
     "opts": ["Crouzon syndrome", "Apert syndrome", "Carpenter syndrome", "Pfeiffer syndrome"],
     "ans": 0, "exp": "Crouzon: craniosynostosis + midface hypoplasia + proptosis WITHOUT syndactyly (Apert = with mitten syndactyly; Carpenter = with polydactyly/obesity/hypogonadism). (Book p44)"},

    # ---------------- CH10 · Abnormalities of Stature (p45-47) ----------------
    {"ch": 10, "unit": "PEDS-U089",
     "stem": "A 4-year-old boy is very short with short proximal limbs (rhizomelia), a relatively normal trunk, lumbar lordosis and a trident hand. Upper segment:lower segment ratio is increased.",
     "q": "The most likely diagnosis is —",
     "opts": ["Achondroplasia", "Spondyloepiphyseal dysplasia", "Growth hormone deficiency", "Congenital hypothyroidism"],
     "ans": 0, "exp": "Achondroplasia: short proximal limbs (rhizomelia) → short limbs with normal trunk → ↑ US:LS. (SED shortens the trunk → ↓ US:LS; GH deficiency/hypothyroidism are proportionate.) (Book p45-46)"},
    {"ch": 10, "unit": "PEDS-U090",
     "stem": "An 11-year-old boy is on the 3rd percentile for height with delayed puberty. His bone age is 9 years (delayed). His father had a similar 'late bloomer' pattern and reached normal adult height.",
     "q": "The most likely diagnosis is —",
     "opts": ["Constitutional delay of growth", "Familial short stature", "Growth hormone deficiency", "Hypothyroidism"],
     "ans": 0, "exp": "Constitutional delay: delayed bone age + delayed puberty + positive family history, normal adult height (Familial short stature = short with NORMAL bone age; GH deficiency = abnormal velocity). (Book p46)"},
    {"ch": 10, "unit": "PEDS-U090",
     "stem": "A 6-year-old girl is tall for her age with pubic hair, clitoromegaly and advanced bone age. Her height was normal at 3 years.",
     "q": "The most likely cause is —",
     "opts": ["Congenital adrenal hyperplasia", "Constitutional delay of growth", "Familial tall stature", "Hypothyroidism"],
     "ans": 0, "exp": "Virilization + accelerated growth + advanced bone age = excess androgens — congenital adrenal hyperplasia (bone age advanced; in most other short stature causes BA is delayed). (Book p46-47)"},
    {"ch": 10, "unit": "PEDS-U093",
     "stem": "A 14-year-old tall boy has long limbs, lens dislocation detected on eye examination (inferior/bilateral), intellectual disability and a positive family history. Homocysteine is elevated in urine.",
     "q": "The most likely diagnosis is —",
     "opts": ["Homocystinuria", "Marfan syndrome", "Klinefelter syndrome", "Sotos syndrome"],
     "ans": 0, "exp": "Homocystinuria (cystathionine-β-synthase deficiency): marfanoid habitus + INFERIOR lens dislocation + intellectual disability; Marfan has superior dislocation with normal intellect. (Book p47)"},

    # ---------------- CH11 · Normal Development (p48-51) ----------------
    {"ch": 11, "unit": "PEDS-U094",
     "stem": "A 5-month-old baby brought for immunization cannot hold her head up at all when pulled to sit, and keeps her head lagging in ventral suspension. She was born at term.",
     "q": "This finding is —",
     "opts": ["Abnormal — head control appears by 3-4 months", "Normal — head control comes by 8 months", "Normal in a girl baby", "A variant of no significance"],
     "ans": 0, "exp": "Head control/neck holding is achieved by 3 months; absence at 5 months is a red flag for neuromuscular disease (e.g., cerebral palsy). (Book p48)"},
    {"ch": 11, "unit": "PEDS-U096",
     "stem": "During a developmental assessment of an 18-month-old, he stacks 3 cubes, scribbles spontaneously and uses a mature pincer grasp with tidbit foods.",
     "q": "Which of his skills is age-appropriate exactly as expected at 18 months?",
     "opts": ["Tower of 3 cubes", "Tower of 6 cubes", "Copying a circle", "Drawing a diamond"],
     "ans": 0, "exp": "Tower of cubes: 15 months = 2, 18 months = 3, 2 years = 6, 3 years = 9. Circle is copied at 3 years, diamond at 6-7 years. (Book p48-49)"},
    {"ch": 11, "unit": "PEDS-U097",
     "stem": "A 2-year-old speaks only 8-10 single meaningful words with no two-word phrases. His motor, social and fine motor milestones are all age-appropriate, and he follows commands well.",
     "q": "This pattern is best described as —",
     "opts": ["Isolated language delay", "Global developmental delay", "Developmental regression", "Developmental deviance"],
     "ans": 0, "exp": "At 2 years a child should have ~100 words and speak in sentences; delay confined to one domain (language) with other domains normal = isolated (dissociated) language delay. (Book p49)"},
    {"ch": 11, "unit": "PEDS-U098",
     "stem": "A 4-month-old does not smile in response to his mother's face and does not fix or follow a red rattle. He was born at term without complications.",
     "q": "The next step is —",
     "opts": ["Detailed developmental and visual assessment", "Reassure and review after 6 months", "No action — he is too young", "Start visual stimulation exercises only"],
     "ans": 0, "exp": "Social smile appears by 2 months and visual fixation/following by 2 months; absence at 4 months is a red flag needing evaluation. (Book p49)"},

    # ---------------- CH12 · Disorders of Development (p52-53) ----------------
    {"ch": 12, "unit": "PEDS-U102",
     "stem": "An 18-month-old has a developmental age of 12 months on formal testing. She was born at term and has no dysmorphism.",
     "q": "Her developmental quotient (DQ) is —",
     "opts": ["66 — developmental delay", "84 — normal", "150 — advanced", "90 — borderline normal"],
     "ans": 0, "exp": "DQ = (DA/CA) × 100 = (12/18) × 100 = 66; DQ < 70 = developmental delay. (Book p51)"},
    {"ch": 12, "unit": "PEDS-U103",
     "stem": "Four children attend a development clinic. Which of these findings is a RED FLAG that demands urgent evaluation?",
     "q": "Choose the red flag sign —",
     "opts": ["No head control at 5 months", "Not walking alone at 14 months", "No two-word phrases at 20 months", "Only 5 words at 16 months"],
     "ans": 0, "exp": "Red-flag upper limits: head control 5 months, sitting without support 10 months, walking/standing without support + single words 18 months. Not walking at 14 months is still normal. (Book p51)"},
    {"ch": 12, "unit": "PEDS-U106",
     "stem": "A 2.5-year-old girl who had normal early development lost purposeful hand use at 18 months and now has repetitive hand-wringing movements; her head circumference has stopped growing.",
     "q": "The most likely diagnosis is —",
     "opts": ["Rett syndrome", "Autism spectrum disorder", "Cerebral palsy", "Duchenne muscular dystrophy"],
     "ans": 0, "exp": "Rett syndrome (MECP-2, X-linked dominant): regression with loss of purposeful hand use + stereotypic hand-wringing + acquired microcephaly after 1 year. (Book p52)"},
    {"ch": 12, "unit": "PEDS-U106",
     "stem": "A 3-month-old baby rolls over completely but has not yet achieved head control, and lower limbs are hypertonic with scissoring.",
     "q": "This pattern of development is called —",
     "opts": ["Deviance", "Dissociation", "Regression", "Global delay"],
     "ans": 0, "exp": "Deviance = abnormal QUALITY/sequence of development — early rolling before head control due to increased extensor tone (a pointer towards cerebral palsy). (Book p52)"},

    # ---------------- CH13 · Behavioural Disorders (p54-57) ----------------
    {"ch": 13, "unit": "PEDS-U107",
     "stem": "A 14-month-old cries after a minor injury, holds his breath, becomes pale and briefly loses consciousness with transient tonic posturing. He recovers fully within a minute.",
     "q": "For recurrent such episodes, the recommended evaluation is —",
     "opts": ["ECG to rule out long QT syndrome", "EEG to rule out epilepsy", "CT scan of the brain", "Serum calcium and glucose"],
     "ans": 0, "exp": "Pallid breath-holding spells: if persistent, do ECG to rule out long QT syndrome (may mimic the event; treatment of BHS itself is reassurance). (Book p53)"},
    {"ch": 13, "unit": "PEDS-U109",
     "stem": "A 3-year-old from a low-income family persistently eats mud and peeled paint from walls. He is pale and irritable.",
     "q": "The most important evaluation is —",
     "opts": ["Hemoglobin and blood lead levels", "Stool examination and culture", "EEG for absence seizures", "Serum vitamin B12 level"],
     "ans": 0, "exp": "Pica (eating non-food items): evaluate and treat iron deficiency anaemia; lead exposure (paint) must also be assessed. (Book p54)"},
    {"ch": 13, "unit": "PEDS-U112",
     "stem": "An 8-year-old has had frequent eye blinking and throat-clearing for the past 14 months. The movements worsen with stress, disappear during sleep, and he can suppress them briefly.",
     "q": "The most likely diagnosis is —",
     "opts": ["Tourette syndrome", "Transient simple tic", "Sydenham chorea", "Myoclonic epilepsy"],
     "ans": 0, "exp": "Tourette: multiple motor tics + a vocal tic lasting ≥ 1 year, onset < 18 years, absent during sleep (transient tics last < 1 year). (Book p55)"},
    {"ch": 13, "unit": "PEDS-U114",
     "stem": "A 7-year-old wets the bed nightly but has never been dry at night and is otherwise completely normal on examination and urinalysis.",
     "q": "The first line of management is —",
     "opts": ["Behavioural therapy with reassurance", "Immediate oral desmopressin", "Long-term oxybutynin", "Imipramine at bedtime"],
     "ans": 0, "exp": "Primary nocturnal enuresis: first line = reassurance + behavioural therapy (star chart, evening fluid restriction, wakening); desmopressin only for short term; imipramine is NOT used (cardiovascular adverse effects). (Book p56)"},

    # ---------------- CH14 · Breastfeeding (p58-61) ----------------
    {"ch": 14, "unit": "PEDS-U115",
     "stem": "A mother complains of painful nipples while breastfeeding her 5-day-old baby. On examination, the baby's mouth is wide open with lips flanged, more areola visible above the baby's mouth than below, and the chin touches the breast.",
     "q": "The sign of GOOD attachment in this baby is —",
     "opts": ["More areola visible above the mouth", "Dimpled cheeks while suckling", "Clicking sound during feeds", "Nipple pointed downward in the mouth"],
     "ans": 0, "exp": "Good attachment: mouth wide open, lower lip everted, chin touching breast, more areola seen ABOVE the mouth; dimpled cheeks/clicking/nausea indicate poor attachment. (Book p57)"},
    {"ch": 14, "unit": "PEDS-U120",
     "stem": "A 2-month-old is exclusively breastfed. The mother asks which supplements are routinely needed. The baby received vitamin K at birth.",
     "q": "The routine daily supplement indicated is —",
     "opts": ["Vitamin D", "Vitamin C", "Iron drops", "Calcium syrup"],
     "ans": 0, "exp": "Breastmilk is deficient in Vitamin D (and Vitamin K at birth, and B12 in vegan mothers) — so exclusively breastfed babies need routine Vitamin D supplementation. (Book p59)"},
    {"ch": 14, "unit": "PEDS-U119",
     "stem": "A mother delivers her first baby. On day 2, she notices thick, yellow, scanty milk. She is told it is rich in immunoglobulins and protein.",
     "q": "This milk is called —",
     "opts": ["Colostrum", "Transitional milk", "Mature milk", "Foremilk"],
     "ans": 0, "exp": "Colostrum (days 1-4): thick, yellow, scanty, rich in protein, IgA, Vitamin A and anti-infective proteins (mnemonic 3As). (Book p58)"},
    {"ch": 14, "unit": "PEDS-U122",
     "stem": "A 2-week-old has prolonged jaundice, failure to thrive, cataracts and E. coli urinary sepsis. Reducing substances are present in the urine while on breastmilk (lactose-containing).",
     "q": "Breastfeeding is absolutely contraindicated in —",
     "opts": ["Galactosemia", "Phenylketonuria", "Maternal hepatitis B infection", "Cleft lip and palate"],
     "ans": 0, "exp": "Galactosemia (galactose-1-phosphate uridyltransferase deficiency): lactose-containing breastmilk must be stopped (absolute contraindication). (Book p60)"},

    # ---------------- CH15 · Malnutrition (p62-65) ----------------
    {"ch": 15, "unit": "PEDS-U126",
     "stem": "A 17-month-old weighs 6.4 kg and has bilateral pitting pedal oedema, sparse easily-pluckable hair, depigmented skin patches and a miserable, irritable demeanour.",
     "q": "This child has —",
     "opts": ["Kwashiorkor (edematous SAM)", "Marasmus", "Marasmic-kwashiorkor", "Simple underweight"],
     "ans": 0, "exp": "Oedema + apathy/irritability + hair/skin changes with fair weight = kwashiorkor (edematous SAM); marasmus = severe wasting without oedema. (Book p61)"},
    {"ch": 15, "unit": "PEDS-U126",
     "stem": "A 14-month-old is measured at an anganwadi. MUAC is 10.8 cm, weight-for-height z-score is −2.4, and there is no oedema. She is alert and feeding.",
     "q": "The correct classification and plan is —",
     "opts": ["SAM — needs inpatient management", "MAM — community-based management", "Normal nutrition", "Overweight for height"],
     "ans": 0, "exp": "SAM criteria: MUAC < 11.5 cm OR WFH < −3 SD OR bilateral pitting oedema. MUAC 10.8 = SAM (irrespective of WFH −2.4). (Book p62)"},
    {"ch": 15, "unit": "PEDS-U129",
     "stem": "A child with severe acute malnutrition is admitted lethargic with a capillary glucose of 36 mg/dL in Phase I (stabilisation).",
     "q": "Hypoglycemia in SAM is treated with —",
     "opts": ["IV 10% dextrose 5 mL/kg, then feeds", "IV 10% dextrose 2 mL/kg only", "Oral sugar solution alone", "IV 25% dextrose 4 mL/kg"],
     "ans": 0, "exp": "SAM protocol: suspected/symptomatic hypoglycemia → IV 10% dextrose 5 mL/kg STAT followed by immediate feeding (2-3 hourly feeds to prevent recurrence). (Book p63)"},
    {"ch": 15, "unit": "PEDS-U130",
     "stem": "It is day 3 of Phase I stabilisation for a child with SAM. The team reviews micronutrient supplementation.",
     "q": "The micronutrient deliberately DEFERRED (not given) in Phase I is —",
     "opts": ["Iron", "Vitamin A", "Folic acid", "Zinc"],
     "ans": 0, "exp": "Phase I micronutrients: Vitamin A, Zinc, Folic acid, Copper (multivitamins). Iron is NOT given in Phase I — it is started only in Phase II (rehabilitation) once the child is stable. (Book p63)"},

    # ---------------- CH16 · Obesity (p66-68) ----------------
    {"ch": 16, "unit": "PEDS-U131",
     "stem": "A 7-year-old boy weighs 30 kg with a height of 1.20 m. His BMI plots above the 95th percentile for age and sex on the IAP chart.",
     "q": "This child is classified as —",
     "opts": ["Obese", "Overweight", "Normal for age", "At risk of overweight"],
     "ans": 0, "exp": "BMI (weight kg / height m²) > 95th percentile for age/sex = obesity; 85th-95th percentile = overweight (BMI 20.8 here). (Book p66)"},
    {"ch": 16, "unit": "PEDS-U135",
     "stem": "A 4-year-old has severe early-onset obesity with uncontrollable hyperphagia. History reveals neonatal hypotonia with poor feeding; he has almond-shaped eyes, small hands and feet, and undescended testes.",
     "q": "The most likely diagnosis is —",
     "opts": ["Prader-Willi syndrome", "Beckwith-Wiedemann syndrome", "Bardet-Biedl syndrome", "Cushing syndrome"],
     "ans": 0, "exp": "Prader-Willi (imprinting disorder): neonatal hypotonia/poor feeding → hyperphagia + obesity, almond eyes, small hands/feet, hypogonadism. (Book p68)"},
    {"ch": 16, "unit": "PEDS-U135",
     "stem": "A 5-year-old with obesity also has polydactyly, night blindness from retinal dystrophy, and learning difficulty.",
     "q": "The most likely syndromic obesity is —",
     "opts": ["Bardet-Biedl syndrome", "Prader-Willi syndrome", "Beckwith-Wiedemann syndrome", "ROHHAD syndrome"],
     "ans": 0, "exp": "Laurence-Moon-Bardet-Biedl: obesity + polydactyly + retinal dystrophy + hypogonadism/intellectual disability. (Book p68)"},
    {"ch": 16, "unit": "PEDS-U136",
     "stem": "A 12-year-old with obesity has a dark, velvety, thickened pigmentation over the neck and axillae. Blood pressure is at the 95th percentile and she snores at night.",
     "q": "The skin finding (acanthosis nigricans) indicates —",
     "opts": ["Insulin resistance", "Androgen excess", "Cortisol excess", "Growth hormone excess"],
     "ans": 0, "exp": "Acanthosis nigricans in obesity = insulin resistance (marker of type 2 diabetes risk); she also has hypertension and probable OSA — all obesity complications. (Book p68)"},

    # ---------------- CH17 · Rickets and Scurvy (p69-73) ----------------
    {"ch": 17, "unit": "PEDS-U139",
     "stem": "A 14-month-old, exclusively breastfed with no vitamin D supplementation, has widened wrists and ankles, a rachitic rosary, frontal bossing and open anterior fontanelle. She is starting to walk with bowed legs.",
     "q": "The most likely diagnosis is —",
     "opts": ["Nutritional vitamin D deficiency rickets", "Vitamin D dependent rickets type I", "Familial hypophosphatemic rickets", "Scurvy"],
     "ans": 0, "exp": "Exclusively breastfed + no Vit D supplementation + classic deformities (rosary, frontal bossing, wide wrists, delayed fontanelle closure) = nutritional rickets. (Book p69)"},
    {"ch": 17, "unit": "PEDS-U140",
     "stem": "A wrist X-ray of a toddler with rickets shows the metaphyseal end of the radius and ulna to be widened, cupped and frayed with ragged margins.",
     "q": "These X-ray changes indicate —",
     "opts": ["Active rickets", "Scurvy (Trümmerfeld zone)", "Healing rickets", "Osteopetrosis"],
     "ans": 0, "exp": "Active rickets X-ray: cupping, fraying and widening of the metaphyses with ragged margins (scurvy instead shows subperiosteal haemorrhage, Trümmerfeld zone, Pelken spur). (Book p70-71)"},
    {"ch": 17, "unit": "PEDS-U143",
     "stem": "A 2-year-old with refractory rickets also has total alopecia. Labs: hypophosphatemia with HIGH 1,25-dihydroxy vitamin D levels.",
     "q": "The most likely diagnosis is —",
     "opts": ["VDDR type II (receptor defect)", "VDDR type I", "Nutritional rickets", "Familial hypophosphatemic rickets"],
     "ans": 0, "exp": "VDDR type II: end-organ resistance to vitamin D → high calcitriol + alopecia (unique feature); type I = low calcitriol (1α-hydroxylase deficiency). (Book p72)"},
    {"ch": 17, "unit": "PEDS-U144",
     "stem": "An 18-month-old fed only boiled cow milk is irritable with bleeding gums, perifollicular haemorrhages and corkscrew hair. She refuses to move her legs, keeping hips and knees semi-flexed. X-ray shows subperiosteal haemorrhage.",
     "q": "The treatment of this condition is —",
     "opts": ["Oral vitamin C 100-200 mg/day", "Vitamin D 3000 IU/day", "Vitamin K injection", "Oral vitamin B12"],
     "ans": 0, "exp": "Scurvy (vitamin C deficiency — boiled milk diet, bleeding gums, corkscrew hair, painful legs with frog-leg posture/pseudoparalysis): treat with oral vitamin C 100-200 mg/day until lesions subside. (Book p73)"},

    # ---------------- CH18 · Genetic Disorders (p74-79) ----------------
    {"ch": 18, "unit": "PEDS-U145",
     "stem": "A dysmorphic newborn has hypotonia, upslanting palpebral fissures, epicanthal folds, a single palmar crease, and a 'double bubble' sign on abdominal X-ray.",
     "q": "The expected karyotype is —",
     "opts": ["47,XX,+21 (non-disjunction)", "47,XX,+18", "45,X", "46,XX,t(14;21)"],
     "ans": 0, "exp": "Down syndrome features + duodenal atresia; ~95% are due to non-disjunction (47,+21), 4% Robertsonian translocation, 1% mosaicism. (Book p74-75)"},
    {"ch": 18, "unit": "PEDS-U148",
     "stem": "A 15-year-old girl is short, has a webbed neck, low posterior hairline, shield chest with widely spaced nipples, cubitus valgus and primary amenorrhea. FSH is elevated.",
     "q": "The most likely karyotype is —",
     "opts": ["45,X (Turner syndrome)", "47,XXY (Klinefelter)", "47,XX,+18", "46,XX"],
     "ans": 0, "exp": "Turner syndrome: 45,X — short girl, webbed neck, shield chest, cubitus valgus, streak ovaries (hypergonadotropic hypogonadism). (Book p76-77)"},
    {"ch": 18, "unit": "PEDS-U150",
     "stem": "A newborn has cyanotic congenital heart disease with recurrent hypocalcemic seizures; chest X-ray shows an absent thymic shadow and the baby has cleft palate.",
     "q": "The most likely diagnosis is —",
     "opts": ["DiGeorge syndrome (22q11 deletion)", "Down syndrome", "Williams syndrome", "Noonan syndrome"],
     "ans": 0, "exp": "CATCH-22: Cardiac defects, Abnormal facies, Thymic aplasia (T-cell deficiency), Cleft palate, Hypocalcemia — 22q11 microdeletion. (Book p78)"},
    {"ch": 18, "unit": "PEDS-U152",
     "stem": "A boy has intellectual disability, elongated face, large protruding ears, macro-orchidism and a family history of intellectual disability in males.",
     "q": "The genetic defect is —",
     "opts": ["FMR1 CGG trinucleotide repeat expansion", "MECP-2 mutation", "22q11 microdeletion", "7q11.23 microdeletion"],
     "ans": 0, "exp": "Fragile X (m/c inherited intellectual disability): FMR1 CGG repeat → long face, large ears, macroorchidism. (MECP-2 = Rett; 7q11.23 = Williams.) (Book p79)"},

    # ---------------- CH19 · Childhood Infections (p80-85) ----------------
    {"ch": 19, "unit": "PEDS-U154",
     "stem": "A 3-year-old unvaccinated child has fever, cough, coryza and conjunctivitis for 3 days. Today, bluish-white spots on an erythematous base were seen on the buccal mucosa opposite the molars.",
     "q": "Management should include vitamin A —",
     "opts": ["1 lakh IU, 2 doses 24 hours apart", "50,000 IU single dose", "2 lakh IU daily for a week", "1/2 lakh IU, 2 doses 24 hours apart"],
     "ans": 0, "exp": "Measles (Koplik spots): vitamin A reduces morbidity/mortality by 50%; dose 1 lakh IU if > 1 year (1/2 lakh if < 1 year), 2 doses 24 hours apart. (Book p81)"},
    {"ch": 19, "unit": "PEDS-U155",
     "stem": "A 6-year-old has fever, sore throat and a fine sandpaper-like rash that spares the palms and soles, with a strawberry tongue and Pastia's lines in the elbow creases.",
     "q": "The treatment of choice is —",
     "opts": ["Oral penicillin V for 10 days", "Oral amoxicillin for 3 days", "IV ceftriaxone single dose", "Oral acyclovir"],
     "ans": 0, "exp": "Scarlet fever (Group A β-hemolytic streptococci): oral Penicillin V for 10 days (> Amoxicillin 10 days) to prevent rheumatic fever. (Book p81)"},
    {"ch": 19, "unit": "PEDS-U158",
     "stem": "A 10-month-old has had high-grade fever for 3 days with no other findings and a normal examination; today the fever has subsided and a rose-pink macular rash has appeared on the trunk.",
     "q": "The most likely diagnosis is —",
     "opts": ["Roseola infantum", "Measles", "Rubella", "Scarlet fever"],
     "ans": 0, "exp": "Roseola (HHV-6): high fever 3 days → rash appears ON DEFERVESCENCE (rose-pink macules, trunk); post-auricular nodes, Nagayama spots may be seen. (Book p84)"},
    {"ch": 19, "unit": "PEDS-U160",
     "stem": "An unvaccinated 5-year-old develops itchy lesions in crops — macules, vesicles, pustules and crusts all present together — with low-grade fever.",
     "q": "The most likely diagnosis is —",
     "opts": ["Varicella (chickenpox)", "Measles", "Erythema infectiosum", "Hand-foot-mouth disease"],
     "ans": 0, "exp": "Varicella: polymorphic lesions in different stages (crops) with centripetal distribution and fever. (Book p84-85)"},

    # ---------------- CH20 · TORCH Infections (p86-91) ----------------
    {"ch": 20, "unit": "PEDS-U163",
     "stem": "A newborn has microcephaly, 'blueberry muffin' purpura, sensorineural hearing loss and periventricular intracranial calcifications. The mother had a flu-like illness in late pregnancy.",
     "q": "The most likely congenital infection is —",
     "opts": ["Cytomegalovirus", "Toxoplasmosis", "Rubella", "Zika virus"],
     "ans": 0, "exp": "Periventricular calcification + SNHL = congenital CMV (most common congenital infection); toxo gives diffuse calcification + chorioretinitis; Zika gives collapsing skull + microcephaly. (Book p87)"},
    {"ch": 20, "unit": "PEDS-U164",
     "stem": "A newborn has the triad of chorioretinitis, hydrocephalus and diffuse intracranial calcifications. The mother keeps cats and ate undercooked meat during pregnancy.",
     "q": "The treatment of this baby includes —",
     "opts": ["Pyrimethamine + sulfadiazine + folinic acid", "Ganciclovir for 6 weeks", "Aqueous penicillin G", "Acyclovir IV"],
     "ans": 0, "exp": "Congenital toxoplasmosis: pyrimethamine + sulfadiazine (1 year) + folic/folinic acid to prevent marrow suppression; spiramycin is used in the infected MOTHER to decrease transmission. (Book p89)"},
    {"ch": 20, "unit": "PEDS-U162",
     "stem": "A newborn has a cataract, a patent ductus arteriosus, sensorineural deafness and a salt-and-pepper retinopathy with purpura. The mother had a faint rash in the first trimester.",
     "q": "The most likely diagnosis is —",
     "opts": ["Congenital rubella syndrome", "Congenital CMV infection", "Congenital toxoplasmosis", "Congenital syphilis"],
     "ans": 0, "exp": "CRS triad: cataract + cardiac (PDA) + SNHL, plus salt-and-pepper retinopathy, blueberry muffin/purpura; risk is highest with 1st-trimester maternal infection. (Book p86-87)"},
    {"ch": 20, "unit": "PEDS-U166",
     "stem": "A 2-week-old has a persistent blood-tinged nasal discharge (snuffles), a vesiculobullous rash on the palms and soles, hepatosplenomegaly and pseudoparalysis of one arm. X-ray shows metaphyseal changes of the long bones.",
     "q": "The treatment of choice is —",
     "opts": ["Aqueous crystalline penicillin G", "Erythromycin estolate", "Doxycycline", "Ceftriaxone single dose"],
     "ans": 0, "exp": "Early congenital syphilis (snuffles, palmar/plantar rash, osteochondritis): aqueous crystalline penicillin G (> ceftriaxone as 3rd gen alternative); diagnosis VDRL in baby AND mother. (Book p90)"},
]
