"""PULSE Paediatrics — hand-crafted ODD-ONE-OUT bank.
Three options share a property; one does not. `exp` names the shared property
so the review screen teaches the grouping, not just the answer.
Inserted at the end of the target unit by audit.py.
"""

ODD = [
    # CH1
    {"ch": 1, "unit": "PEDS-U013",
     "q": "Odd one out (newborn head swellings after birth):",
     "opts": ["Caput succedaneum", "Cephalohematoma", "Subgaleal hemorrhage", "Mongolian spot"],
     "ans": 0, "exp": "Caput/cephalohematoma/subgaleal are birth-related scalp swellings; a Mongolian spot is a pigmented dermal lesion (melanocytes arrested in dermis) — not a head swelling. (Book p5-6)"},
    {"ch": 1, "unit": "PEDS-U009",
     "q": "Odd one out (components of the APGAR score):",
     "opts": ["Grimace", "Activity (tone)", "Respiratory effort", "Ponderal index"],
     "ans": 0, "exp": "APGAR = Activity, Pulse, Grimace, Appearance, Respiratory effort; ponderal index assesses IUGR type, not APGAR. (Book p4)"},
    # CH2
    {"ch": 2, "unit": "PEDS-U015",
     "q": "Odd one out (golden-minute priorities after birth):",
     "opts": ["Airway", "Temperature", "Circulation", "Phototherapy"],
     "ans": 0, "exp": "Golden minute: 1st respiration, 2nd temperature, 3rd circulation; phototherapy treats jaundice, not a resuscitation priority. (Book p7)"},
    {"ch": 2, "unit": "PEDS-U021",
     "q": "Odd one out (MRSOPA corrective steps for poor BMV chest rise):",
     "opts": ["Mask adjustment", "Reposition airway", "Suction mouth and nose", "Chest compression"],
     "ans": 0, "exp": "MRSOPA = Mask adjustment, Reposition, Suction, Open mouth, Pressure increase, Alternative airway; chest compression is for HR < 60, not a ventilation-correction step. (Book p9)"},
    # CH3
    {"ch": 3, "unit": "PEDS-U028",
     "q": "Odd one out (causal agents of EARLY-onset neonatal sepsis):",
     "opts": ["Group B Streptococcus", "E. coli", "Listeria monocytogenes", "Rotavirus"],
     "ans": 0, "exp": "Early-onset sepsis (< 72 h) is bacterial — GBS, E. coli, Listeria; rotavirus is an enteric virus causing diarrhoea, not neonatal sepsis. (Book p13)"},
    {"ch": 3, "unit": "PEDS-U026",
     "q": "Odd one out (IV antibiotic cover in NEC):",
     "opts": ["Penicillin (gram-positive)", "Aminoglycoside (gram-negative)", "Metronidazole (anaerobe)", "Vitamin A"],
     "ans": 0, "exp": "NEC management: NPO + IV antibiotics covering gram-positive (penicillin), gram-negative (aminoglycoside) and anaerobes (metronidazole); vitamin A is a micronutrient, not an antibiotic. (Book p12)"},
    # CH4
    {"ch": 4, "unit": "PEDS-U035",
     "q": "Odd one out (causes of respiratory distress in the newborn):",
     "opts": ["TTNB", "RDS (hyaline membrane disease)", "MAS", "Necrotizing enterocolitis"],
     "ans": 0, "exp": "TTNB/RDS/MAS are respiratory causes of newborn distress; NEC is a gastrointestinal disease (though it may present with apnoea, its primary system is gut). (Book p17)"},
    {"ch": 4, "unit": "PEDS-U032",
     "q": "Odd one out (clinical signs of respiratory distress):",
     "opts": ["Grunting", "Nasal flaring", "Intercostal retraction", "Cephalohematoma"],
     "ans": 0, "exp": "Grunting, nasal flaring and retractions signal respiratory distress; cephalohematoma is a sub-periosteal collection of blood after instrumental delivery. (Book p16)"},
    # CH5
    {"ch": 5, "unit": "PEDS-U044",
     "q": "Odd one out (causes of UNCONJUGATED jaundice):",
     "opts": ["Physiological jaundice", "Breast milk jaundice", "ABO haemolysis", "Biliary atresia"],
     "ans": 0, "exp": "Physiological/breast-milk/haemolytic jaundice are unconjugated; biliary atresia causes CONJUGATED (direct) hyperbilirubinaemia with pale stools. (Book p22)"},
    {"ch": 5, "unit": "PEDS-U042",
     "q": "Odd one out (tools for assessment of neonatal jaundice):",
     "opts": ["Kramer rule", "Transcutaneous bilirubinometry", "Phototherapy normogram", "APGAR score"],
     "ans": 0, "exp": "Kramer (visual zones), TcB and the normogram assess jaundice; APGAR scores the baby's condition at birth. (Book p21-23)"},
    # CH6
    {"ch": 6, "unit": "PEDS-U051",
     "q": "Odd one out (methods of keeping a newborn warm):",
     "opts": ["Kangaroo mother care", "Radiant warmer", "Incubator", "Phototherapy"],
     "ans": 0, "exp": "KMC/warmer/incubator prevent hypothermia (stable vs unstable baby); phototherapy TREATS jaundice (and actually adds warmth as a side effect). (Book p25-26)"},
    {"ch": 6, "unit": "PEDS-U055",
     "q": "Odd one out (drugs used in resistant neonatal hypoglycemia):",
     "opts": ["Diazoxide", "Octreotide", "Glucagon", "Surfactant"],
     "ans": 0, "exp": "Diazoxide/octreotide ↓ insulin; glucagon/hydrocortisone stimulate gluconeogenesis — all treat resistant hypoglycemia; surfactant treats RDS. (Book p28)"},
    # CH7
    {"ch": 7, "unit": "PEDS-U057",
     "q": "Odd one out (primitive reflexes of the newborn):",
     "opts": ["Moro reflex", "Palmar grasp", "Asymmetric tonic neck reflex", "Parachute reflex"],
     "ans": 0, "exp": "Moro/palmar grasp/ATNR are PRIMITIVE reflexes (present at birth, disappear early); parachute is a POSTURAL reflex appearing at 6-9 months and persisting. (Book p30-31)"},
    {"ch": 7, "unit": "PEDS-U061",
     "q": "Odd one out (features of Sarnat staging of HIE):",
     "opts": ["Hyperalertness (stage I)", "Seizures in first 24-48 h (stage II)", "Hypotonia with depressed reflexes", "Frontal bossing"],
     "ans": 0, "exp": "Hyperalertness, early seizures and hypotonia map to Sarnat stages; frontal bossing is a skeletal feature of rickets, unrelated to HIE. (Book p32)"},
    # CH8
    {"ch": 8, "unit": "PEDS-U066",
     "q": "Odd one out (stages of prenatal growth):",
     "opts": ["Zygote", "Embryo", "Fetus", "Gamete"],
     "ans": 0, "exp": "Prenatal phases: zygote (< 2 wks) → embryo (3-8 wks) → fetus (> 9 wks); the gamete exists BEFORE fertilisation. (Book p35)"},
    {"ch": 8, "unit": "PEDS-U074",
     "q": "Odd one out (concepts used in growth monitoring):",
     "opts": ["Catch-up growth", "Catch-down growth", "Growth velocity", "Developmental quotient"],
     "ans": 0, "exp": "Catch-up/catch-down and growth velocity describe GROWTH; developmental quotient (DA/CA × 100) measures development. (Book p39-40)"},
    # CH9
    {"ch": 9, "unit": "PEDS-U084",
     "q": "Odd one out (craniosynostosis syndromes):",
     "opts": ["Crouzon syndrome", "Apert syndrome", "Carpenter syndrome", "Down syndrome"],
     "ans": 0, "exp": "Crouzon/Apert/Carpenter are craniosynostosis syndromes (suture fusion ± syndactyly); Down syndrome is an aneuploidy without premature suture fusion. (Book p44)"},
    {"ch": 9, "unit": "PEDS-U078",
     "q": "Odd one out (teratogenic causes of microcephaly):",
     "opts": ["Fetal alcohol syndrome", "Fetal hydantoin syndrome", "Congenital rubella infection", "Rett syndrome"],
     "ans": 0, "exp": "Alcohol/hydantoin/rubella act as intrauterine teratogens; Rett syndrome has a POSTNATAL onset — head growth stops after 1 year of normal development. (Book p42)"},
    # CH10
    {"ch": 10, "unit": "PEDS-U086",
     "q": "Odd one out (with respect to short stature):",
     "opts": ["Growth hormone deficiency", "Hypothyroidism", "Cushing syndrome", "Constitutional delay"],
     "ans": 0, "exp": "GH deficiency/hypothyroidism/Cushing are pathological causes of short stature; constitutional delay is a NORMAL variant (delayed bone age + delayed puberty, normal adult height). (Book p45)"},
    {"ch": 10, "unit": "PEDS-U089",
     "q": "Odd one out (patterns seen in short stature):",
     "opts": ["Short limbs with normal trunk", "Short trunk with normal limbs", "Proportionate shortening", "Eunuchoid proportions"],
     "ans": 0, "exp": "Short limbs (achondroplasia), short trunk (SED) and proportionate shortening (GH deficiency) are SHORT stature patterns; eunuchoid proportions describe TALL stature with ↑ US:LS. (Book p46)"},
    # CH11
    {"ch": 11, "unit": "PEDS-U094",
     "q": "Odd one out (gross motor milestones):",
     "opts": ["Head control", "Rolling over", "Sitting without support", "Social smile"],
     "ans": 0, "exp": "Head control/rolling/sitting are gross motor milestones; social smile (2 months) is a SOCIAL milestone. (Book p48-49)"},
    {"ch": 11, "unit": "PEDS-U096",
     "q": "Odd one out (achievements of the toddler years):",
     "opts": ["Pincer grasp", "Tower of 3 cubes", "Copying a circle", "Attaining menarche"],
     "ans": 0, "exp": "Pincer grasp (12 m), tower of 3 cubes (18 m) and circle (3 y) belong to early childhood; menarche is a pubertal event (girls ~12-13 y). (Book p48-49)"},
    # CH12
    {"ch": 12, "unit": "PEDS-U106",
     "q": "Odd one out (causes of developmental regression):",
     "opts": ["Rett syndrome", "Subacute sclerosing panencephalitis", "Leukodystrophy", "Down syndrome"],
     "ans": 0, "exp": "Regression (loss of acquired milestones): Rett, SSPE, leukodystrophy; Down syndrome causes delay from birth but NO loss of milestones. (Book p52)"},
    {"ch": 12, "unit": "PEDS-U104",
     "q": "Odd one out (developmental assessment/screening tests):",
     "opts": ["Denver II", "Trivandrum development screening test", "Baroda screening test", "Shakir tape"],
     "ans": 0, "exp": "Denver II/Trivandrum/Baroda (Phatak's) screen development; the Shakir tape measures MUAC for malnutrition. (Book p51)"},
    # CH13
    {"ch": 13, "unit": "PEDS-U114",
     "q": "Odd one out (drugs considered in nocturnal enuresis):",
     "opts": ["Desmopressin", "Oxybutynin", "Tolterodine", "Imipramine"],
     "ans": 0, "exp": "Desmopressin (short term), oxybutynin/tolterodine (long term) are options in enuresis; imipramine is NOT used because of adverse cardiovascular effects. (Book p56)"},
    {"ch": 13, "unit": "PEDS-U109",
     "q": "Odd one out (benign behavioural variations of childhood):",
     "opts": ["Pica", "Bruxism", "Thumb sucking", "Infantile spasms"],
     "ans": 0, "exp": "Pica/bruxism/thumb sucking are benign habit disorders managed with reassurance; infantile spasms is an EPILEPTIC encephalopathy needing treatment. (Book p54-55)"},
    # CH14
    {"ch": 14, "unit": "PEDS-U119",
     "q": "Odd one out (types of human breast milk):",
     "opts": ["Colostrum", "Transitional milk", "Mature milk", "Cow milk"],
     "ans": 0, "exp": "Colostrum → transitional → mature milk are the phases of human breast milk; cow milk is an animal milk (unmodified, unsuitable < 1 year). (Book p58)"},
    {"ch": 14, "unit": "PEDS-U120",
     "q": "Odd one out (nutrients in which breast milk is deficient):",
     "opts": ["Vitamin K", "Vitamin B12", "Vitamin D", "Vitamin C"],
     "ans": 0, "exp": "Breast milk is deficient in vitamin K, B12 (vegan mothers) and D; vitamin C is present in adequate amounts in breast milk. (Book p59)"},
    # CH15
    {"ch": 15, "unit": "PEDS-U130",
     "q": "Odd one out (micronutrients given in Phase I of SAM management):",
     "opts": ["Vitamin A", "Folic acid", "Zinc", "Iron"],
     "ans": 0, "exp": "Phase I gives vitamin A, folic acid, zinc and multivitamins; IRON is withheld in Phase I and started in Phase II once stabilised. (Book p63)"},
    {"ch": 15, "unit": "PEDS-U126",
     "q": "Odd one out (criteria for SEVERE acute malnutrition):",
     "opts": ["MUAC < 11.5 cm", "WFH z-score < −3 SD", "Bilateral pitting oedema", "Weight-for-age < −2 SD"],
     "ans": 0, "exp": "SAM = MUAC < 11.5 cm OR WFH < −3 SD OR bilateral pitting oedema; weight-for-age < −2 SD is 'underweight' (a different classification). (Book p62)"},
    # CH16
    {"ch": 16, "unit": "PEDS-U133",
     "q": "Odd one out (pathological causes of obesity):",
     "opts": ["Leptin deficiency", "MC4R gene defect", "Prader-Willi syndrome", "Exogenous obesity"],
     "ans": 0, "exp": "Leptin deficiency/MC4R (monogenic) and PWS (syndromic) are pathological obesity; exogenous (simple) obesity is the common non-pathological form. (Book p67-68)"},
    {"ch": 16, "unit": "PEDS-U136",
     "q": "Odd one out (complications of obesity):",
     "opts": ["Acanthosis nigricans", "Obstructive sleep apnea", "Systemic hypertension", "Koplik spots"],
     "ans": 0, "exp": "Acanthosis (insulin resistance), OSA and hypertension are obesity complications; Koplik spots are the pathognomonic enanthem of measles. (Book p68)"},
    # CH17
    {"ch": 17, "unit": "PEDS-U139",
     "q": "Odd one out (signs of rickets):",
     "opts": ["Craniotabes", "Rachitic rosary", "Frontal bossing", "Koplik spots"],
     "ans": 0, "exp": "Craniotabes/rosary/frontal bossing are rachitic signs; Koplik spots indicate measles. (Book p69)"},
    {"ch": 17, "unit": "PEDS-U144",
     "q": "Odd one out (features of scurvy):",
     "opts": ["Bleeding gums", "Pseudoparalysis of limbs", "Frog-leg posture", "Genu varum (bow legs)"],
     "ans": 0, "exp": "Gum bleeds, painful pseudoparalysis and frog-leg posture are scurvy (vitamin C deficiency); genu varum is a deformity of RICKETS (vitamin D deficiency). (Book p73)"},
    # CH18
    {"ch": 18, "unit": "PEDS-U145",
     "q": "Odd one out (with respect to chromosomal basis):",
     "opts": ["Down syndrome", "Edwards syndrome", "Patau syndrome", "Turner syndrome"],
     "ans": 0, "exp": "Down/Edwards/Patau are autosomal TRISOMIES (21, 18, 13); Turner is sex-chromosome MONOSOMY (45,X). (Book p74-76)"},
    {"ch": 18, "unit": "PEDS-U146",
     "q": "Odd one out (associations of Down syndrome):",
     "opts": ["Duodenal atresia", "Endocardial cushion defect", "Hirschsprung disease", "Clutton's joints"],
     "ans": 0, "exp": "Duodenal atresia, AV canal defects and Hirschsprung are Down associations; Clutton's joints (bilateral knee effusions) belong to CONGENITAL SYPHILIS. (Book p74-75)"},
    # CH19
    {"ch": 19, "unit": "PEDS-U154",
     "q": "Odd one out (enanthems of exanthematous diseases):",
     "opts": ["Koplik spots", "Nagayama spots", "Forchheimer spots", "Pastia's lines"],
     "ans": 0, "exp": "Koplik (measles), Nagayama (roseola) and Forchheimer (rubella) are mucosal ENANTHEMS; Pastia's lines are haemorrhagic streaks in skin creases (scarlet fever) — an exanthem. (Book p80-84)"},
    {"ch": 19, "unit": "PEDS-U153",
     "q": "Odd one out (maculopapular childhood exanthems):",
     "opts": ["Measles", "Rubella", "Roseola infantum", "Varicella"],
     "ans": 0, "exp": "Measles/rubella/roseola are maculopapular exanthems; varicella is a VESICULAR exanthem (lesions in crops at different stages). (Book p80-84)"},
    # CH20
    {"ch": 20, "unit": "PEDS-U166",
     "q": "Odd one out (features of congenital syphilis):",
     "opts": ["Snuffles", "Hutchinson's teeth", "Clutton's joints", "Salt-and-pepper retinopathy"],
     "ans": 0, "exp": "Snuffles/ Hutchinson's teeth/Clutton's joints are syphilitic; salt-and-pepper retinopathy is a feature of CONGENITAL RUBELLA. (Book p87, 90)"},
    {"ch": 20, "unit": "PEDS-U162",
     "q": "Odd one out (features of congenital rubella syndrome):",
     "opts": ["Cataract", "Patent ductus arteriosus", "Sensorineural hearing loss", "Periventricular calcification"],
     "ans": 0, "exp": "Cataract + PDA + SNHL form the CRS triad; periventricular calcification is characteristic of CONGENITAL CMV. (Book p86-87)"},
]
