CH = 16
UNITS = [
    {"id": "PEDS-U131", "ch": 16, "n": 1, "title": "Obesity — Introduction and Definitions", "sec": "Obesity · p66", "qs": [], "guide": "Obesity Excess adipose tissue deposition Seen >20% children urban India Energy intake >> expenditure ↑↑ deposition primarily abdomen (Central obesity ↑↑ risk complications) Note body unlimited capacity for fats, not carbs/proteins. DEFINITIONS BMI >5 yrs Wt kg/Ht m2 x100 plotted BMI charts Overweight >23 adult eq Obesity >27 adult eq. Wt for Ht <5 yrs WHO charts +2 to +3 SD Overweight >+3 SD Obesity. Skinfold ↑subcutaneous fat Harpenden caliper >85th %ile Obesity. Waist circumference indicator abdominal obesity >75th %ile >80 cm girls >90 cm boys. Waist-hip ratio age independent >1 males >0.85 females. Waist-height ratio age independent >0.5 obesity. BMI interpretation per IAP BMI chart."},
    {"id": "PEDS-U132", "ch": 16, "n": 2, "title": "Etiology — Constitutional (Exogenous) vs Pathological", "sec": "ETIOLOGY · p66", "qs": [], "guide": "Obesity 2 branches Constitutional (Exogenous) m/c vs Pathological. Constitutional Cause Excess food intake + Inadequate exercise. Characteristics Child has Tall stature d/t ↑insulin and ↑Insulin-like Growth Factor (IGF) + Generalized obesity. Pathological Usually child is of short stature."},
    {"id": "PEDS-U133", "ch": 16, "n": 3, "title": "Pathological Obesity — Monogenic and Endocrine Causes", "sec": "Causes of Pathological Obesity · p67", "qs": [], "guide": "1. Monogenic Hereditary single gene defects (Positive family history) a. mineralocorticoid-4-receptor defect (MC4R) m/c b. Leptin deficiency ↓leptin/resistance to leptin → uncontrolled appetite. Note Leptin deficiency first reported monogenic cause. 2. Endocrine Cushing's (Truncal obesity + buffalo hump + striae + moon-face) Hypothyroidism Pseudohypoparathyroidism Growth hormone deficiency."},
    {"id": "PEDS-U134", "ch": 16, "n": 4, "title": "Hypothalamic Obesity and ROHHAD Mnemonic", "sec": "Hypothalamic Obesity · p67", "qs": [], "guide": "3. Hypothalamic obesity Lesion in Ventro-medial nucleus (VMN) Satiety centre → uncontrolled appetite. Causes Head injury, Radiation, Tumor, Infection. ROHHAD mnemonic R Rapid Onset, O Obesity with, H Hypothalamic dysfunction, H Hypoventilation, A Autonomic, D Dysregulation."},
    {"id": "PEDS-U135", "ch": 16, "n": 5, "title": "Syndromic Obesity and Drug Causes", "sec": "Syndromic Obesity · p67", "qs": [], "guide": "4. Syndromic a. Prader-Willi Syndrome Genetic imprinting disorder Features Hypogonadism, small hands & feet, almond-shaped eyes. b. Beckwith-Wiedemann Obesity, Macroglossia, Organomegaly, Hemi hypertrophy. c. Laurence-Moon (LM) + Biedl-Bardet (BB) shared Obesity, Hypogonadism, Intellectual disability, Retinitis pigmentosa; LM Syndactyly; BB Polydactyly. 5. Drugs Anti-epileptic (Valproate, Lamotrigine) Steroids → Cushingoid appearance."},
    {"id": "PEDS-U136", "ch": 16, "n": 6, "title": "Complications of Obesity", "sec": "Complications · p68", "qs": [], "guide": "Metabolic complications Obesity (↑adipose) → Insulin resistance → Metabolic syndrome/Syndrome X + PCOS in women. Insulin resistance marker Acanthosis nigricans (Hyperpigmented velvety patches on neck and axilla). Non-Alcoholic Fatty Liver Disease (NAFLD) Leads to Steatohepatitis (Inflammatory changes in liver) → Chronic → Fibrosis."},
    {"id": "PEDS-U137", "ch": 16, "n": 7, "title": "Management of Obesity — Lifestyle, Medical, Surgical", "sec": "Management of Obesity · p68", "qs": [], "guide": "Steps Lifestyle changes → (No response) Medical management → (No response) Surgical management. Lifestyle Sugars avoid processed (sweetened beverages, packaged foods) Fats avoid trans + saturated ↑ unsaturated ↑ vegetables fruits nuts grains Salt <5 g/day Physical activity moderate-strenuous >60 min/day (>30 min school hours). Medical Treatment of endocrine disorders Orlistat (inhibits gastric & pancreaticlipase ↓ fat breakdown & absorption) GLP-1 analogue Liraglutide (slows gastric emptying ↓ fat absorption) Metformin (Known diabetes, Women with PCOS). Surgical Last resort LAGB ↓ capacity stomach ↓ Food intake."},
]

def q(num, sec, page, qtext, opts, ans, exp):
    assert len(opts)==4 and 0 <= ans <4
    return {"id": f"PEDS-C16-{num:03d}", "sec": sec, "page": page, "q": qtext, "opts": opts, "ans": ans, "exp": exp}

QUESTIONS = [
    q(1,"PEDS-U131",66,"Obesity is defined as",["Excess of adipose tissue deposition","Excess muscle deposition","Excess water retention","Excess bone mass"],0,"Excess of adipose tissue deposition (Book p66)"),
    q(2,"PEDS-U131",66,"Obesity is seen in what % of children in urban India?",[">20% children","<5% children","~50% children","All children"],0,"Seen in >20% children in urban India (Book p66)"),
    q(3,"PEDS-U131",66,"Obesity results from",["Energy intake >> expenditure","Energy intake << expenditure","Equal intake and expenditure","Increased expenditure"],0,"Energy intake >> expenditure (Book p66)"),
    q(4,"PEDS-U131",66,"In obesity, adipose is deposited primarily in the",["Abdomen (Central obesity)","Arms","Calves","Face"],0,"↑↑ deposition of adipose primarily in the abdomen (Central Obesity) (Book p66)"),
    q(5,"PEDS-U131",66,"Central obesity carries",["↑↑ risk of complications","↓ risk of complications","No risk","Equal risk"],0,"Central Obesity: ↑↑ risk of complications (Book p66)"),
    q(6,"PEDS-U131",66,"Note on body storage capacity",["Body has unlimited capacity for storage of fats, but not carbohydrates or proteins","Unlimited for all nutrients","Unlimited for proteins only","Limited for fats"],0,"Body has unlimited capacity for storage of fats, but not carbohydrates or proteins (Book p66 Note)"),
    q(7,"PEDS-U131",66,"Body mass index is used for children",[">5 yrs","<5 yrs","<1 yr","Any age, same interpretation"],0,"Body mass index: For children >5 yrs (Book p66)"),
    q(8,"PEDS-U131",66,"BMI formula",["Weight (in kg) / Height (in m²) × 100","Weight / Height × 10","Height / Weight × 100","Weight × Height / 100"],0,"BMI = Weight (in kg)/Height (in m²) ×100 (Book p66)"),
    q(9,"PEDS-U131",66,"BMI values are",["Plotted in BMI charts","Compared to adults directly","Compared to WHO Wt for age","Fixed cutoff 25/30"],0,"(Plotted in BMI charts) (Book p66)"),
    q(10,"PEDS-U131",66,"BMI interpretation — Overweight",[">23 adult equivalent",">27 adult equivalent","<18.5","30-35"],0,"Overweight: >23 adult equivalent (Book p66)"),
    q(11,"PEDS-U131",66,"BMI interpretation — Obesity",[">27 adult equivalent",">23 adult equivalent","<23","=30"],0,"Obesity: >27 adult equivalent (Book p66)"),
    q(12,"PEDS-U131",66,"Weight for height is used for children",["<5 yrs",">5 yrs","<2 yrs only",">10 yrs"],0,"Weight for height: For children <5 yrs (Book p66)"),
    q(13,"PEDS-U131",66,"Measurement used for weight for height",["WHO weight for height charts","IAP BMI charts","Harpenden caliper","Waist-hip ratio"],0,"WHO weight for height charts (Book p66)"),
    q(14,"PEDS-U131",66,"Weight for height — Overweight",["+2 to +3 SD",">+3 SD","-2 to -3 SD","< -3 SD"],0,"+2 to +3 SD: Overweight (Book p66)"),
    q(15,"PEDS-U131",66,"Weight for height — Obesity",[">+3 SD","+2 to +3 SD","-2 to -3 SD","< -3 SD"],0,">+3 SD: Obesity (Book p66)"),
    q(16,"PEDS-U131",66,"Skinfold thickness measures",["↑ subcutaneous fat","Visceral fat only","Muscle mass","Bone mass"],0,"Skinfold thickness ↑ subcutaneous fat (Book p66)"),
    q(17,"PEDS-U131",66,"Skinfold thickness is measured with",["Harpenden caliper","Tape measure","Pedometer","Stadiometer"],0,"Harpenden caliper (Book p66)"),
    q(18,"PEDS-U131",66,"Skinfold thickness — Obesity",[">85th percentile",">75th percentile",">90th percentile",">50th percentile"],0,">85th percentile: Obesity (Book p66)"),
    q(19,"PEDS-U131",66,"Waist circumference is an indicator of",["Abdominal obesity","Limb obesity","Generalized obesity","Neck obesity"],0,"Indicator of abdominal obesity (Book p66)"),
    q(20,"PEDS-U131",66,"Waist circumference — Obesity interpretation",[">75th percentile; >80 cm in girls; >90 cm in boys",">90 cm girls >80 cm boys",">75 cm both",">50th percentile"],0,">75th percentile; >80 cm in girls; >90 cm in boys (Book p66)"),
    q(21,"PEDS-U131",66,"Waist-hip ratio",["Age independent; ratio of waist circumference to hip circumference","Age dependent; weight/hip","Waist/height","Weight/waist"],0,"Waist-hip ratio: Age independent; Ratio of waist circumference to hip circumference (Book p66)"),
    q(22,"PEDS-U131",66,"Waist-hip ratio — Obesity",[">1 in males; >0.85 in females",">0.85 males >1 females",">1.5 both",">0.5 both"],0,">1 in males, >0.85 in females (Book p66)"),
    q(23,"PEDS-U131",66,"Waist-height ratio — Obesity",["Age independent; >0.5 = obesity","Age dependent; >1","<0.5","=0.75"],0,"Waist-height ratio: Age independent; >0.5 - obesity (Book p66)"),
    q(24,"PEDS-U131",66,"BMI interpretation is based on",["Indian Association of Paediatrics (IAP) BMI chart","WHO adult BMI","WHO Wt for age","AHI chart"],0,"Note: BMI interpretation is based on the Indian Association of Paediatrics BMI chart (Book p66)"),
    q(25,"PEDS-U132",66,"Etiology of obesity is divided into",["Constitutional (Exogenous) m/c + Pathological","Only pathological","Only genetic","Only endocrine"],0,"Obesity → Constitutional (Exogenous): m/c; Pathological (Book p66)"),
    q(26,"PEDS-U132",66,"Most common cause of obesity in children",["Constitutional (Exogenous)","Monogenic","Prader-Willi","Hypothalamic"],0,"Constitutional (Exogenous): m/c (Book p66)"),
    q(27,"PEDS-U132",66,"Causes of Constitutional (exogenous) obesity",["Excess food intake + Inadequate exercise","Only genetic defect","Only hypothyroidism","Only tumors"],0,"Cause: a. Excess food intake b. Inadequate exercise (Book p66)"),
    q(28,"PEDS-U132",66,"Characteristics of child with constitutional obesity",["Tall stature (d/t ↑insulin and ↑IGF) + Generalized obesity","Short stature + central obesity","Normal stature","Delayed bone age"],0,"Child has a. Tall stature due to ↑ insulin and ↑ Insulin-like Growth Factor (IGF) b. Generalized obesity (Book p66)"),
    q(29,"PEDS-U132",66,"Tall stature in constitutional obesity is due to",["↑ insulin and ↑ Insulin-like Growth Factor (IGF)","↓ insulin","Hypothyroidism","GH deficiency"],0,"Tall stature due to ↑ insulin and ↑ Insulin-like Growth Factor (IGF) (Book p66)"),
    q(30,"PEDS-U132",66,"In pathological obesity, the child is",["Usually of short stature","Always tall","Always normal stature","Always premature"],0,"Pathological: Usually, child is of short stature (Book p66)"),
    q(31,"PEDS-U133",67,"Monogenic causes of pathological obesity",["Hereditary single gene defects (Positive family history)","Chromosomal disorders only","Environmental exposure","Infections"],0,"1. Monogenic causes: Hereditary single gene defects (Positive family history) (Book p67)"),
    q(32,"PEDS-U133",67,"m/c monogenic (single gene) defect in obesity",["mineralocorticoid-4-receptor defect (MC4R)","Leptin deficiency","Leprechin defect","Pro-opiomelanocortin defect"],0,"a. mineralocorticoid-4-receptor defect (MC4R): m/c (Book p67)"),
    q(33,"PEDS-U133",67,"Leptin deficiency in obesity means",["↓ leptin/resistance to leptin","↑ leptin action","Normal leptin with receptor excess","Only resistance to insulin"],0,"b. Leptin deficiency: ↓ leptin/resistance to leptin (Book p67)"),
    q(34,"PEDS-U133",67,"Leptin deficiency/resistance leads to",["Uncontrolled appetite","Reduced appetite","Anorexia","Normal satiety"],0,"↓ leptin/resistance to leptin → uncontrolled appetite (Book p67)"),
    q(35,"PEDS-U133",67,"First reported monogenic cause of obesity",["Leptin deficiency","MC4R defect","Ghrelin excess","Cholesteryl ester storage"],0,"Note: Leptin deficiency was the first reported monogenic cause of obesity (Book p67)"),
    q(36,"PEDS-U133",67,"Endocrine causes of pathological obesity",["Cushing's syndrome, Hypothyroidism, Pseudohypoparathyroidism, Growth hormone deficiency","Only acromegaly","Only DM","Only Addison's"],0,"2. Endocrine causes: Cushing's syndrome, Hypothyroidism, Pseudohypoparathyroidism, Growth hormone deficiency (Book p67)"),
    q(37,"PEDS-U133",67,"Cushing's syndrome features in this book",["Truncal obesity + buffalo hump + striae + moon-face","Generalized obesity only","Eccentric hypertrophy","Marfanoid habitus"],0,"Cushing's syndrome: Truncal obesity + buffalo hump + striae + moon-face (Book p67)"),
    q(38,"PEDS-U134",67,"Hypothalamic obesity is due to lesion in",["Ventro-medial nucleus (VMN)","Lateral nucleus","Supraoptic nucleus","Pituitary gland"],0,"Lesion in Ventro-medial nucleus (VMN) (Book p67)"),
    q(39,"PEDS-U134",67,"Ventro-medial nucleus (VMN) of hypothalamus is the",["Satiety centre","Hunger centre","Thirst centre","Thermoregulatory centre"],0,"VMN: Satiety centre (Book p67)"),
    q(40,"PEDS-U134",67,"Lesion of VMN leads to",["Uncontrolled appetite","Reduced appetite","Anorexia","Normal appetite"],0,"Satiety centre → uncontrolled appetite (Book p67)"),
    q(41,"PEDS-U134",67,"Causes of hypothalamic obesity",["Head injury, Radiation, Tumor, Infection","Only head injury","Only radiation","Only infection"],0,"Causes: Head injury, Radiation, Tumor, Infection (Book p67)"),
    q(42,"PEDS-U134",67,"ROHHAD is the mnemonic for hypothalamic obesity of",["Rapid Onset, Obesity with, Hypothalamic dysfunction, Hypoventilation, Autonomic Dysregulation","Only Rapid onset Hypothalamic disorders","Only hypothalamic tumors","Only radiation injury"],0,"ROHHAD: mnemonic (Rapid onset Obesity with Hypothalamic dysfunction, Hypoventilation, Autonomic Dysregulation) (Book p67)"),
    q(43,"PEDS-U134",67,"ROHHAD — R stands for",["Rapid Onset","Radiation injury","Retinitis pigmentosa","Rapid weight loss"],0,"R: Rapid Onset (Book p67)"),
    q(44,"PEDS-U134",67,"ROHHAD — O stands for",["Obesity with","Only truncal obesity","Organomegaly","Ovarian failure"],0,"O: Obesity with (Book p67)"),
    q(45,"PEDS-U134",67,"ROHHAD — first H stands for",["Hypothalamic dysfunction","Hypoventilation","Hyperglycemia","Hypothyroidism"],0,"H: Hypothalamic dysfunction (Book p67)"),
    q(46,"PEDS-U134",67,"ROHHAD — second H stands for",["Hypoventilation","Hypothalamic dysfunction","Hypernatremia","Hypertension"],0,"H: Hypoventilation (Book p67)"),
    q(47,"PEDS-U134",67,"ROHHAD — A stands for",["Autonomic","Anemia","Achalasia","Ataxia"],0,"A: Autonomic (Book p67)"),
    q(48,"PEDS-U134",67,"ROHHAD — D stands for",["Dysregulation","Diabetes","Dysphagia","Demyelination"],0,"D: Dysregulation (Book p67)"),
    q(49,"PEDS-U135",67,"Prader-Willi Syndrome is a",["Genetic imprinting disorder","X-linked disorder","Chromosomal deletion 5p","Mitochondrial disorder"],0,"a. Prader-Willi Syndrome: Genetic imprinting disorder (Book p67)"),
    q(50,"PEDS-U135",67,"Prader-Willi Syndrome clinical features",["Hypogonadism, small hands & feet, almond-shaped eyes","Tall stature + long limbs","Macroglossia","Polydactyly"],0,"Clinical features: Hypogonadism, small hands & feet, almond-shaped eyes (Book p67)"),
    q(51,"PEDS-U135",67,"Beckwith-Wiedemann syndrome clinical features",["Obesity, Macroglossia, Organomegaly, Hemi hypertrophy","Almond eyes","Syndactyly","Retinitis pigmentosa"],0,"b. Beckwith-Wiedemann syndrome: Clinical features Obesity, Macroglossia, Organomegaly, Hemi hypertrophy (Book p67 image)"),
    q(52,"PEDS-U135",67,"Shared clinical features of Laurence-Moon (LM) and Biedl-Bardet (BB) syndrome",["Obesity, Hypogonadism, Intellectual disability, Retinitis pigmentosa","Macroglossia only","Almond-shaped eyes","Small hands & feet"],0,"c. LM + BB syndrome: Clinical features Obesity, Hypogonadism, Intellectual disability, Retinitis pigmentosa (Book p67)"),
    q(53,"PEDS-U135",67,"Laurence-Moon (LM) syndrome is distinguished by",["Syndactyly","Polydactyly","Macroglossia","Retinitis pigmentosa only"],0,"LM → Syndactyly (Book p67)"),
    q(54,"PEDS-U135",67,"Biedl-Bardet (BB) syndrome is distinguished by",["Polydactyly","Syndactyly","Macroglossia","Organomegaly"],0,"BB → Polydactyly (Book p67)"),
    q(55,"PEDS-U135",68,"Drug causes of obesity (anti-epileptics)",["Eg. Valproate, Lamotrigine","Ceftriaxone, Amoxicillin","Ondansetron","Amiodarone"],0,"5. Drugs: Anti-epileptic drugs: Eg. Valproate, Lamotrigine (Book p68)"),
    q(56,"PEDS-U135",68,"Steroids cause",["Cushingoid appearance","Marfanoid habitus","Klippel-Feil","Scurvy"],0,"Steroids → Cushingoid appearance (Book p68)"),
    q(57,"PEDS-U136",68,"Metabolic complications of obesity begin with",["Obesity (↑ adipose) → Insulin resistance","Hypothyroidism","GH excess","Acanthosis nigricans first"],0,"Obesity (↑ adipose) → Insulin resistance (Book p68)"),
    q(58,"PEDS-U136",68,"Insulin resistance in obesity leads to",["Metabolic syndrome/Syndrome X + PCOS in women","Hypertrophic cardiomyopathy","Cleft palate","Rickets"],0,"→ Metabolic syndrome/Syndrome X; PCOS in women (Book p68)"),
    q(59,"PEDS-U136",68,"Marker of insulin resistance in obesity",["Acanthosis nigricans","Gynaecomastia","Hirsutism only","Moon face"],0,"Insulin resistance → marker → Acanthosis nigricans (Book p68)"),
    q(60,"PEDS-U136",68,"Acanthosis nigricans appears as",["Hyperpigmented velvety patches on neck and axilla","Flaky-paint desquamation","White striae","Cafe-au-lait spots"],0,"Acanthosis nigricans (Hyperpigmented velvety patches on neck and axilla) (Book p68)"),
    q(61,"PEDS-U136",68,"Non-Alcoholic Fatty Liver Disease (NAFLD) leads to",["Steatohepatitis (Inflammatory changes in liver)","Cirrhosis directly without steatohepatitis","Hepatocellular adenoma","Wilson's disease"],0,"NAFLD: Leads to Steatohepatitis (Inflammatory changes in liver) (Book p68)"),
    q(62,"PEDS-U136",68,"Chronic steatohepatitis leads to",["Fibrosis","Necrosis only","Hemochromatosis","Amyloidosis"],0,"Steatohepatitis → Chronic → Fibrosis (Book p68)"),
    q(63,"PEDS-U137",68,"Steps in management of obesity (if no response)",["Lifestyle changes → Medical management → Surgical management","Surgery first","Medical first","Diet alone forever"],0,"Lifestyle changes → (No response) Medical management → (No response) Surgical management (Book p68)"),
    q(64,"PEDS-U137",68,"Lifestyle change — Sugars",["Avoid processed sugar (Sweetened beverages, Packaged foods)","Encourage sweets","Sugar only in tea","No restriction"],0,"a. Sugars: Avoid processed sugar - Sweetened beverages, Packaged foods (Book p68)"),
    q(65,"PEDS-U137",68,"Lifestyle change — Fats to avoid",["Trans fatty acid + Saturated fatty acid","Unsaturated fatty acid","Omega-3","No fats at all"],0,"b. Fats: Avoid fats like Trans fatty acid, Saturated fatty acid (Book p68)"),
    q(66,"PEDS-U137",68,"Lifestyle change — Fats to encourage",["↑ intake of Unsaturated fatty acid","Trans fatty acid","Saturated fatty acid","No fats"],0, "↑ intake of: Unsaturated fatty acid (Book p68)"),
    q(67,"PEDS-U137",68,"Lifestyle change — ↑ intake of",["Vegetables, fruits; Nuts and grains","Candy, chips","Refined flour","Sugary drinks"],0,"c. ↑ intake of: vegetables, fruits; Nuts and grains (Book p68)"),
    q(68,"PEDS-U137",68,"Lifestyle change — Salt intake",["<5 g/day","<10 g/day","No limit","Zero salt"],0,"d. ↓ intake of salt: <5 g/day (Book p68)"),
    q(69,"PEDS-U137",68,"Lifestyle change — Physical activity target",["Moderate to strenuous; >60 min/day (>30 min in school hours)","10 min/day","No activity","Only swimming"],0,"e. ↑ physical activity: moderate to strenuous physical activity; >60 min/day (>30 min in school hours) (Book p68)"),
    q(70,"PEDS-U137",68,"First step of medical management of obesity",["Treatment of endocrine disorders","Orlistat","Liraglutide","Surgery"],0,"a. Treatment of endocrine disorders (Book p68)"),
    q(71,"PEDS-U137",68,"Orlistat acts by",["Inhibiting gastric & pancreatic lipase → ↓ fat breakdown & absorption","Inhibiting amylase only","Increasing satiety via VMN","Slowing gastric emptying"],0,"b. Orlistat: Inhibits gastric & pancreaticlipase → ↓ fat breakdown & absorption (Book p68)"),
    q(72,"PEDS-U137",68,"GLP-1 analogue used in obesity",["Liraglutide","Orlistat","Metformin","Levothyroxine"],0,"c. GLP-1 analogue: Liraglutide (Book p68)"),
    q(73,"PEDS-U137",68,"Liraglutide acts by",["Slowing gastric emptying → ↓ fat absorption","Inhibiting lipase","Increasing basal metabolism directly","Suppressing leptin"],0,"Slows gastric emptying → ↓ fat absorption (Book p68)"),
    q(74,"PEDS-U137",68,"Metformin in obesity is indicated in",["Known diabetes; Women with PCOS","All children","Only hypothyroidism","Only Cushing's"],0,"d. metformin indicated in: Known diabetes; Women with PCOS (Book p68)"),
    q(75,"PEDS-U137",68,"Surgical management of obesity is a",["Last resort","First resort","Always combined with diet","Only for adolescents"],0,"Last resort (Book p68)"),
    q(76,"PEDS-U137",68,"Surgical procedure for obesity in the book",["Laparoscopically adjustable gastric banding (LAGB)","Gastrectomy","Jejunileostomy","Hepatectomy"],0,"Laparoscopically adjustable gastric banding (LAGB) (Book p68)"),
    q(77,"PEDS-U137",68,"LAGB works by",["↓ capacity of stomach → ↓ Food intake","Removing stomach wall","Bypassing duodenum","Denervation of hunger centre"],0,"↓ capacity of stomach → ↓ Food intake (Book p68)"),
]

RANGES = {131:(1,24),132:(25,30),133:(31,37),134:(38,48),135:(49,56),136:(57,62),137:(63,77)}
UNIT_RANGES = {1:(1,24),2:(25,30),3:(31,37),4:(38,48),5:(49,56),6:(57,62),7:(63,77)}
for u in UNITS:
    s,e = UNIT_RANGES[u["n"]]
    u["qs"] = [f"PEDS-C16-{i:03d}" for i in range(s,e+1)]

pages = [q["page"] for q in QUESTIONS]
assert pages == sorted(pages), f"Pages not sorted {pages[:10]}"
assert len(QUESTIONS)==77
assert len(UNITS)==7
for u in UNITS:
    s,e = UNIT_RANGES[u["n"]]
    assert len(u["qs"])==e-s+1
