CH = 17
UNITS = [
    {"id": "PEDS-U138", "ch": 17, "n": 1, "title": "Rickets — Etiology and Pathophysiology", "sec": "Rickets · p69", "qs": [], "guide": "Rickets Occurs due to Vitamin D deficiency (Sunshine vitamin). Etiology Dietary deficiency (Fish, fish liver oil, egg yolk) Drugs Anti-epileptics (Phenytoin, phenobarbitone, carbamazepine) + Antitubercular (Isoniazid + Rifampicin) ↓ sunlight exposure Malabsorption Chronic liver disease. Pathophysiology Vit D deficiency → ↓ absorption Ca²⁺ & PO₄³⁻ → ↓ mineralization of bone → Weak bones (Disproportionate short stature: Short limbs, Pathological fractures, Deformity) + Cartilage hypertrophy at growth plate → Osteoid expansion → Swelling."},
    {"id": "PEDS-U139", "ch": 17, "n": 2, "title": "Rickets — Deformity: Head and Chest", "sec": "Deformity · p69", "qs": [], "guide": "Head 1. Craniotabes Softening of skull bone, Sponge ball/ping pong ball like consistency. Note Craniotabes also seen in Congenital syphilis, Hydrocephalus, Osteogenesis imperfecta. 2. ↑ size of fontanelles (Wide open) 3. Frontal bone bossing. Chest 1. Costochondral junction widening Rachitic rosary (Painless & round) AKA string of beads appearance. 2. Harrison's sulcus groove d/t pull of diaphragm on weakened ribs."},
    {"id": "PEDS-U140", "ch": 17, "n": 3, "title": "Rickets — Limbs, Other Findings and Investigations", "sec": "Limbs · p70", "qs": [], "guide": "Limbs 1. Widening of wrist 2. Genu varum/bow leg 3. Genu valgum/knock knees 4. Double malleolus sign (Cartilage hypertrophy Swelling above lateral malleolus). Other findings Delayed dentition Seizures/tetany in infants d/t acute hypocalcemia. Blood ↓ Vit D (↓ as HCC) ↓S.Ca²⁺→↑PTH→Normal S.Ca²⁺ ↓S.PO₄³⁻ D/t ↑ bone resorption by PTH ↑ALP. Vit D table Sufficiency >20, Insufficiency 12-20, Deficiency <12 ng/ml. X-Ray primary tool Loss of zone of provisional calcification (ZPC) white line Fraying (First sign) Cupping."},
    {"id": "PEDS-U141", "ch": 17, "n": 4, "title": "Rickets — Treatment and Monitoring Response", "sec": "Treatment · p71", "qs": [], "guide": "1. Daily dose of Vitamin D → Recommended Duration 12 weeks. Dose <1 year 2000 IU/day; >1 year 3000 IU/day. 2. Ca²⁺ supplement 50-75 mg/kg/day. Monitoring 1. X-Ray Preferred method, shows changes by 4 weeks, Healing with line of rickets (1st visible sign) 2. Biochemical investigation shows changes in 12 weeks."},
    {"id": "PEDS-U142", "ch": 17, "n": 5, "title": "Refractory Rickets — Definition and Familial Hypophosphatemic Rickets", "sec": "Refractory Rickets · p71", "qs": [], "guide": "Refractory Rickets No response to Vitamin D supplementation. Disorders seen 1. Familial hypophosphatemic rickets 2. Vitamin D dependent rickets (VDDR) 3. RTA associated rickets 4. CKD associated rickets. Familial hypophosphatemic X-linked dominant, m/c inherited form, PHEX gene mutation (phosphate regulation endopeptidase). Normal PHEX → Endopeptidase → Inactivated phosphatonin (FGF-23); mutation → No endopeptidase → Phosphatonin always active → ↑ PO₄³⁻ excretion urine → Hypophosphatemia. Features Lower limb deformities, No features of hypocalcemia (e.g. Tetany), Dental abnormalities Pulp exposure ↑ risk dental abscess."},
    {"id": "PEDS-U143", "ch": 17, "n": 6, "title": "Refractory Rickets — Treatment, VDDR and Approach Algorithm", "sec": "VDDR · p72", "qs": [], "guide": "Familial hypophosphatemic Treatment 1. Phosphate supplementation Joule solution (elemental phosphates) 2. Burosumab newer drug monoclonal antibody against FGF-23. VDDR Autosomal recessive, Defects in Vit D metabolism → Hypocalcemia. Features Classic rickets + Type II additional Ectodermal defects (Milia, epidermal cysts), Oligodontia (↓ teeth), Alopecia. Treatment Type I α calcidiol (active form of Vit D) + Ca²⁺ supplements; Type II High doses Vit D → partially overcome resistance → improves symptoms. Approach (biochemical values) High PO₄³⁻ → CKD associated (↓ excretion PO₄³⁻); Low PO₄³⁻ → ABG Acidosis(+) → RTA; Acidosis(−) → PTH High (response to ↓Ca²⁺) → VDDR; Normal → Familial hypophosphatemic."},
    {"id": "PEDS-U144", "ch": 17, "n": 7, "title": "Scurvy — Role of Vitamin C, Etiology, Features, X-Ray, Treatment", "sec": "Scurvy · p73", "qs": [], "guide": "Scurvy D/t Vitamin C deficiency. Role of Vit C 1. Collagen formation (Proline + Lysine → Hydroxylation requires Vit C → mature collagen) 2. Wound healing 3. Osteoid/bony trabeculae formation. Etiology Vit C deficient diet (Citrus fruits Lemon orange, Green vegetables) Intake of boiled/evaporated cow milk without fruit/vegetables. Early features Abnormal irritability ↓ appetite Anemia (Vit C needed for iron absorption). Bleeding Characteristic Gum bleeds, Perifollicular bleeding + corkscrew hair, Bone subperiosteal bleeding → Pain(+) → Pseudo paralysis → frog leg posture. Rosary Painful, Sharp or angulated. Diagnosis Mainly clinical; X-Ray Subperiosteal hemorrhage, Area of rarefaction (Trümmerfeld's zone central), Ring epiphysis, White line of Frankel, Pelken's spur (lateral). Treatment Oral Vit C 100-200 mg/day until lesion subsides."},
]

def q(num, sec, page, qtext, opts, ans, exp):
    assert len(opts)==4 and 0 <= ans <4
    return {"id": f"PEDS-C17-{num:03d}", "sec": sec, "page": page, "q": qtext, "opts": opts, "ans": ans, "exp": exp}

QUESTIONS = [
    q(1,"PEDS-U138",69,"Rickets occurs due to",["Vitamin D deficiency (Sunshine vitamin)","Vitamin C deficiency","Calcium excess","Iron deficiency"],0,"Occurs due to vitamin D deficiency (Sunshine vitamin) (Book p69)"),
    q(2,"PEDS-U138",69,"Dietary sources of vitamin D mentioned for rickets",["Fish, fish liver oil, egg yolk","Citrus fruits","Green leafy vegetables","Only milk"],0,"Dietary deficiency (Fish, fish liver oil, egg yolk) (Book p69)"),
    q(3,"PEDS-U138",69,"Anti-epileptic drugs causing rickets",["Phenytoin, phenobarbitone, carbamazepine","Valproate only","Lamotrigine","Levetiracetam"],0,"Drugs - Anti-epileptics: Phenytoin, phenobarbitone, carbamazepine (Book p69)"),
    q(4,"PEDS-U138",69,"Antitubercular drugs causing rickets",["Isoniazid and rifampicin","Streptomycin only","Pyrazinamide","Ethionamide"],0,"Antitubercular drugs: Isoniazid and rifampicin (Book p69)"),
    q(5,"PEDS-U138",69,"Other causes of rickets",["↓ sunlight exposure, Malabsorption, Chronic liver disease","Excess sunlight","High protein diet","Excess exercise"],0,"↓ sunlight exposure; Malabsorption; Chronic liver disease (Book p69)"),
    q(6,"PEDS-U138",69,"Vitamin D deficiency first leads to",["↓ absorption of Ca²⁺ and PO₄³⁻","↑ absorption of Ca²⁺","↓ PTH","Hypercalcemia"],0,"Vitamin D deficiency → ↓ absorption of Ca²⁺ and PO₄³⁻ (Book p69)"),
    q(7,"PEDS-U138",69,"↓ Ca²⁺/PO₄³⁻ absorption leads to",["↓ mineralization of bone","↑ mineralization","Normal bone","Cartilage loss"],0,"→ ↓ mineralization of bone (Book p69)"),
    q(8,"PEDS-U138",69,"↓ mineralization of bone results in",["Weak bones + Cartilage hypertrophy at growth plate","Strong bones","Short stature only","No change"],0,"→ Weak bones; Cartilage hypertrophy at growth plate (Book p69)"),
    q(9,"PEDS-U138",69,"Weak bones cause (as per book)",["Disproportionate short stature: Short limbs, Pathological fractures, Deformity","Tall stature","Long limbs","Normal bone strength"],0,"Weak bones → Disproportionate short stature: Short limbs, Pathological fractures, Deformity (Book p69)"),
    q(10,"PEDS-U138",69,"Cartilage hypertrophy at growth plate leads to",["Osteoid expansion → Swelling","Osteoid shrinkage","Fractures only","No swelling"],0,"Cartilage hypertrophy at growth plate → Osteoid expansion → Swelling (Book p69)"),
    q(11,"PEDS-U139",69,"Craniotabes means",["Softening of skull bone","Thickening of skull bone","Fracture of skull","Calcification of fontanelle"],0,"1. Craniotabes: Softening of skull bone (Book p69)"),
    q(12,"PEDS-U139",69,"Craniotabes consistency",["Sponge ball/ping pong ball like consistency","Hard wood like","Bone-like","Metallic"],0,"Sponge ball/ping pong ball like consistency (Book p69)"),
    q(13,"PEDS-U139",69,"Craniotabes can also be seen in",["Congenital syphilis, Hydrocephalus, Osteogenesis imperfecta","Only rickets","Only meningitis","Only Down syndrome"],0,"Note: Craniotabes can also be seen in: Congenital syphilis, Hydrocephalus, Osteogenesis imperfecta (Book p69)"),
    q(14,"PEDS-U139",69,"Second head deformity in rickets",["↑ size of fontanelles (Wide open)","↓ size of fontanelles","Early closure","Normal fontanelles"],0,"2. ↑ size of fontanelles (Wide open) (Book p69)"),
    q(15,"PEDS-U139",69,"Third head deformity in rickets",["Frontal bone bossing","Parietal bossing only","Occipital flattening","Tortuosity"],0,"3. Frontal bone bossing (Book p69)"),
    q(16,"PEDS-U139",69,"Rachitic rosary is",["Costochondral junction widening (Painless & round)","Aortic narrowing","Cervical rib","Spinal deformity"],0,"1. Costochondral junction widening: Rachitic rosary (Painless & round) (Book p69)"),
    q(17,"PEDS-U139",69,"Rachitic rosary is also known as",["String of beads appearance","Harrison's groove","Double malleolus","Craniotabes"],0,"AKA string of beads appearance (Book p69)"),
    q(18,"PEDS-U139",70,"Harrison's sulcus groove is due to",["Pull of diaphragm on weakened ribs","Fracture of sternum","Costocondral calcification","Diaphragmatic hernia"],0,"2. Harrison's sulcus groove: D/t pull of diaphragm on weakened ribs (Book p70)"),
    q(19,"PEDS-U140",70,"Limb deformity 1 in rickets",["Widening of wrist","Wrist narrowing","Elbow swelling","Finger shortening"],0,"Limbs: 1. Widening of wrist (Book p70)"),
    q(20,"PEDS-U140",70,"Limb deformity 2 in rickets",["Genu varum/bow leg","Genu valgum only","Flat feet","Club foot"],0,"2. Genu varum/bow leg (Book p70)"),
    q(21,"PEDS-U140",70,"Limb deformity 3 in rickets",["Genu valgum/knock knees","Genu varum only","Tarsus valgus","Equinovarus"],0,"3. Genu valgum/knock knees (Book p70)"),
    q(22,"PEDS-U140",70,"Double malleolus sign",["Cartilage hypertrophy (Swelling) above lateral malleolus","Fracture of medial malleolus","Tendonitis","Splenial fracture"],0,"4. Double malleolus sign: Cartilage hypertrophy (Swelling) above lateral malleolus (Book p70)"),
    q(23,"PEDS-U140",70,"Other finding in rickets — dentition",["Delayed dentition","Early dentition","Normal dentition","Anodontia"],0,"Other findings: 1. Delayed dentition (Book p70)"),
    q(24,"PEDS-U140",70,"Seizures or tetany in rickets occurs",["In infants d/t acute hypocalcemia","In adults d/t hypercalcemia","Always d/t fever","Due to hypokalemia"],0,"2. Seizures or tetany: In infants d/t acute hypocalcemia (Book p70)"),
    q(25,"PEDS-U140",70,"Blood investigation — Vitamin D in rickets",["↓ Vitamin D (↓ as HCC)","↑ Vitamin D","Normal","Only PTH ↑"],0,"Blood investigations: ↓ Vitamin D: ↓ as HCC (Book p70)"),
    q(26,"PEDS-U140",70,"Serum calcium in rickets (d/t ↓ absorption)",["↓ S. Ca²⁺ → ↑ PTH → Normal S. Ca²⁺","Persistently low Ca","High Ca","Ca ↓ PTH ↓"],0,"D/t ↓ absorption: ↓ S. Ca²⁺ → ↑ PTH → Normal S. Ca²⁺ (Book p70)"),
    q(27,"PEDS-U140",70,"Serum phosphate in rickets",["↓ S. PO₄³⁻","↑ S. PO₄³⁻","Normal","Only K⁺ ↓"],0,"↓ S. PO₄³⁻ (Book p70)"),
    q(28,"PEDS-U140",70,"ALP in rickets is",["↑ (d/t ↑ bone resorption by PTH)","↓","Normal","Zero"],0,"D/t ↑ bone resorption by PTH: ↑ ALP (Book p70)"),
    q(29,"PEDS-U140",70,"Classification of vitamin D is based on",["Serum Vit D levels","Bone age only","X-ray only","Clinical signs only"],0,"Note: Classification based on Vit D levels, Serum Vit D levels (Book p70)"),
    q(30,"PEDS-U140",70,"Serum vitamin D — Sufficiency",[">20 ng/ml","12-20 ng/ml","<12 ng/ml","=30 ng/ml"],0,"Sufficiency >20 (Book p70)"),
    q(31,"PEDS-U140",70,"Serum vitamin D — Insufficiency",["12-20 ng/ml",">20 ng/ml","<12 ng/ml","=25 ng/ml"],0,"Insufficiency 12-20 (Book p70)"),
    q(32,"PEDS-U140",70,"Serum vitamin D — Deficiency",["<12 ng/ml",">20 ng/ml","12-20 ng/ml","=10 ng/ml"],0,"Deficiency <12 (Book p70)"),
    q(33,"PEDS-U140",70,"Primary tool of diagnosis of rickets",["X-Ray","MRI","USG","Bone scan"],0,"Radiological investigation: X-Ray: Primary tool of diagnosis (Book p70)"),
    q(34,"PEDS-U140",70,"Loss of zone of provisional calcification (ZPC) appears as",["White line at end of long bone","Dark area at diaphysis","Cupping of epiphysis","Fraying of metaphysis"],0,"Loss of zone of provisional calcification (ZPC): White line at end of long bone (Book p70)"),
    q(35,"PEDS-U140",70,"Fraying in rickets X-ray",["Lateral deviation of ends — First sign; Irregularity at ends","Central calcification","Early closure","Periosteal reaction"],0,"Fraying: Lateral deviation of ends (First sign): Irregularity at ends (Book p70)"),
    q(36,"PEDS-U140",70,"Another X-ray finding of rickets",["Cupping","Hypoplasia","Sclerosis","Widening only"],0,"Cupping (Book p70 image)"),
    q(37,"PEDS-U141",71,"Recommended treatment of rickets",["Daily dose of Vitamin D","Stress dose IM weekly","Calcium only","Iron"],0,"1. Daily dose of vitamin D → Recommended (Book p71)"),
    q(38,"PEDS-U141",71,"Duration of daily vitamin D in rickets",["12 weeks","4 weeks","6 months","1 week"],0,"Duration: 12 weeks (Book p71)"),
    q(39,"PEDS-U141",71,"Vitamin D dose in rickets — age <1 year",["2000 IU/day","3000 IU/day","1000 IU/day","5000 IU/day"],0,"Age <1 year: 2000 IU/day (Book p71)"),
    q(40,"PEDS-U141",71,"Vitamin D dose in rickets — age >1 year",["3000 IU/day","2000 IU/day","1000 IU/day","6000 IU/day"],0,"Age >1 year: 3000 IU/day (Book p71)"),
    q(41,"PEDS-U141",71,"Calcium supplement in rickets",["50-75 mg/kg/day","10-20 mg/kg/day","100-150 mg/kg/day","250 mg/kg/day"],0,"2. Ca²⁺ supplement: 50-75 mg/kg/day (Book p71)"),
    q(42,"PEDS-U141",71,"Preferred method of monitoring response in rickets",["X-Ray","Serum Ca only","Clinical exam only","MRI"],0,"Monitoring response: 1. X-Ray: Preferred method (Book p71)"),
    q(43,"PEDS-U141",71,"X-ray changes appear in rickets by",["4 weeks","1 week","12 weeks","6 months"],0,"Shows changes by 4 weeks (Book p71)"),
    q(44,"PEDS-U141",71,"Healing sign in rickets X-ray",["Healing with line of rickets (1st visible sign)","Loss of ZPC","Cupping","Fraying"],0,"Healing with line of rickets (1st visible sign) (Book p71)"),
    q(45,"PEDS-U141",71,"Biochemical changes in rickets treatment show in",["12 weeks","4 weeks","1 week","48 hours"],0,"2. Biochemical investigation: Shows changes in 12 weeks (Book p71)"),
    q(46,"PEDS-U142",71,"Refractory rickets is",["No response to vitamin D supplementation","Responds to low dose Vit D","Mild rickets","X-ray only diagnosis"],0,"Refractory Rickets: No response to vitamin D supplementation (Book p71)"),
    q(47,"PEDS-U142",71,"Disorders seen in refractory rickets",["Familial hypophosphatemic, VDDR, RTA associated, CKD associated","Only vitamin C deficiency","Only hypothyroidism","Only scurvy"],0,"Disorders seen: 1. Familial hypophosphatemic rickets 2. Vitamin D dependent rickets (VDDR) 3. RTA associated rickets 4. CKD associated rickets (Book p71)"),
    q(48,"PEDS-U142",71,"Inheritance of familial hypophosphatemic rickets",["X-linked dominant","Autosomal recessive","Autosomal dominant","X-linked recessive"],0,"X-linked dominant inheritance (Book p71)"),
    q(49,"PEDS-U142",71,"m/c inherited form of rickets",["Familial hypophosphatemic rickets","VDDR","RTA rickets","CKD rickets"],0,"m/c inherited form of rickets (Book p71)"),
    q(50,"PEDS-U142",71,"Familial hypophosphatemic rickets is due to mutation in",["PHEX gene (Codes for phosphate regulation endopeptidase)","VDR gene","CYP27B1","GnRH receptor"],0,"PHEX gene mutation (Codes for phosphate regulation endopeptidase) (Book p71)"),
    q(51,"PEDS-U142",71,"Normal PHEX gene pathway",["Endopeptidase → Inactivated phosphatonin (Fibroblast growth factor/FGF-23)","Always active phosphatonin","↑ phosphate reabsorption","Direct vitamin D synthesis"],0,"Normal PHEX gene → Endopeptidase → Inactivated phosphatonin (Fibroblast growth factor/FGF-23) (Book p71)"),
    q(52,"PEDS-U142",71,"PHEX mutation leads to",["No endopeptidase → Phosphatonin is always active","More endopeptidase","Inactivated FGF-23","↑ vitamin D"],0,"Normal PHEX gene →(mutation)→ No endopeptidase → Phosphatonin is always active (Book p71)"),
    q(53,"PEDS-U142",71,"Active phosphatonin causes",["↑ PO₄³⁻ excretion in urine → Hypophosphatemia","↓ phosphate excretion","Hypercalcemia","Normal PO₄"],0,"→ ↑ PO₄³⁻ excretion in urine → Hypophosphatemia (Book p71)"),
    q(54,"PEDS-U142",71,"Clinical features of familial hypophosphatemic rickets",["Lower limb deformities; No features of hypocalcemia (e.g. Tetany)","Tetany is prominent","Bleeding gums","Corkscrew hair"],0,"Clinical features: Lower limb deformities; No features of hypocalcemia (Eg: Tetany) (Book p71)"),
    q(55,"PEDS-U142",71,"Dental abnormalities in familial hypophosphatemic rickets",["Pulp exposure, ↑ risk of dental abscess","Enamel hypoplasia only","Early loss of teeth","No dental changes"],0,"Dental abnormalities: Pulp exposure, ↑ risk of dental abscess (Book p71)"),
    q(56,"PEDS-U143",72,"Phosphate supplementation in familial hypophosphatemic rickets",["Joule solution (Contains elemental phosphates)","Oral calcium","Lactose solution","Sodium bicarbonate"],0,"1. Phosphate supplementation: Joule solution (Contains elemental phosphates) (Book p72)"),
    q(57,"PEDS-U143",72,"Burosumab is",["Newer drug: Monoclonal antibody against FGF-23","A vitamin D analogue","An anticonvulsant","A phosphate binder"],0,"2. Burosumab: Newer drug: Monoclonal antibody against FGF-23 (Book p72)"),
    q(58,"PEDS-U143",72,"Inheritance of Vitamin D dependent rickets (VDDR)",["Autosomal recessive","X-linked dominant","Autosomal dominant","Mitochondrial"],0,"Vitamin D dependent rickets (VDDR): Autosomal recessive inheritance (Book p72)"),
    q(59,"PEDS-U143",72,"VDDR is due to",["Defects in vitamin D metabolism → Hypocalcemia","Phosphate wasting","FGF-23 excess","PHEX mutation"],0,"Defects in vitamin D metabolism → Hypocalcemia (Book p72)"),
    q(60,"PEDS-U143",72,"Clinical features of VDDR",["Classic features of rickets","Only alopecia","Only corkscrew hair","Only milia"],0,"Clinical features: 1. Classic features of rickets (Book p72)"),
    q(61,"PEDS-U143",72,"Additional features in Type II VDDR",["Ectodermal defects: Milia, epidermal cysts; Oligodontia (↓ teeth); Alopecia","Rachitic rosary only","Craniotabes only","Gum bleeding"],0,"2. Additional features in Type II VDDR: Ectodermal defects: Milia, epidermal cysts; Oligodontia (↓ teeth); Alopecia (Book p72)"),
    q(62,"PEDS-U143",72,"Treatment of Type I VDDR",["α calcidiol (Active form of vit D) + Ca²⁺ supplements","High dose cholecalciferol","Joule solution","Burosumab"],0,"1. Type I: α calcidiol (Active form of vit D); Ca²⁺ supplements (Book p72)"),
    q(63,"PEDS-U143",72,"Treatment of Type II VDDR",["High doses of Vit D → Partially overcome resistance → Improves symptoms","α calcidiol","Low dose Vit D","Surgery"],0,"2. Type II: High doses of Vit D → Partially overcome resistance → Improves symptoms (Book p72)"),
    q(64,"PEDS-U143",72,"In VDDR Type I, 1α-hydroxylase in kidney is",["Absent","Overactive","Normal","Present but inactive"],0,"Kidney ↓1α-hydroxylase: Absent: Type I (Book p72)"),
    q(65,"PEDS-U143",72,"In VDDR Type II, the problem is",["Resistance to vitamin D metabolism of vitamin D","Absence of 1α-hydroxylase","Low vitamin D intake","Hyperparathyroidism"],0,"Resistance to vitamin D metabolism of vitamin D: Type II (Book p72)"),
    q(66,"PEDS-U143",72,"Approach to refractory rickets is based on",["Biochemical values","Clinical signs only","Age","Family history"],0,"APPROACH TO REFRACTORY RICKETS: Based on biochemical values (Book p72)"),
    q(67,"PEDS-U143",72,"Refractory rickets with High serum PO₄³⁻ is",["CKD associated rickets (↓ excretion of PO₄³⁻)","VDDR","RTA","Familial hypophosphatemic"],0,"High → CKD associated rickets (↓ excretion of PO₄³⁻) (Book p72)"),
    q(68,"PEDS-U143",72,"Refractory rickets with Low PO₄³⁻ and Acidosis (+) on ABG is",["Renal tubular acidosis","VDDR","CKD","Familial hypophosphatemic"],0,"Low → Arterial blood gases → Acidosis(+) → Renal tubular acidosis (Book p72)"),
    q(69,"PEDS-U143",72,"Refractory rickets with Low PO₄³⁻, Acidosis (−), and High PTH (response to ↓ Ca²⁺) is",["VDDR","Familial hypophosphatemic","RTA","CKD"],0,"Acidosis(−) → PTH → High (Response to ↓ Ca²⁺) → VDDR (Book p72)"),
    q(70,"PEDS-U143",72,"Refractory rickets with Low PO₄³⁻, Acidosis (−), and Normal PTH is",["Familial hypophosphatemic rickets","VDDR","RTA","CKD"],0,"PTH Normal → Familial hypophosphatemic rickets (Book p72)"),
    q(71,"PEDS-U144",73,"Scurvy is due to",["Vitamin C deficiency","Vitamin D deficiency","Vitamin A deficiency","Folic acid deficiency"],0,"Scurvy: D/t vitamin C deficiency (Book p73)"),
    q(72,"PEDS-U144",73,"Role of vitamin C — collagen formation requires",["Proline and lysine → Hydroxylation (Requires vitamin C) → mature collagen","Glycine only","No hydroxylation","Calcium"],0,"1. Collagen formation: Proline and lysine ↓ Hydroxylation (Requires vitamin C) → mature collagen (Book p73)"),
    q(73,"PEDS-U144",73,"Other roles of vitamin C",["Wound healing; Osteoid/bony trabeculae formation","Bone resorption","Iron excretion","Collagen degradation"],0,"2. Wound healing; 3. Osteoid/bony trabeculae formation (Book p73)"),
    q(74,"PEDS-U144",73,"Foods rich in vitamin C",["Citrus fruits (Lemon, orange) + Green vegetables","Fish liver oil","Egg yolk","Rice"],0,"Vit C deficient diet, food rich in vit C: Citrus fruits: Lemon, orange; Green vegetables (Book p73)"),
    q(75,"PEDS-U144",73,"Scurvy etiology — milk related",["Intake of boiled/evaporated cow milk (without fruit/vegetables)","Breast milk excess","Only formula","Goat milk"],0,"2. Intake of boiled/evaporated cow milk (without fruit/vegetables) (Book p73)"),
    q(76,"PEDS-U144",73,"Early features of scurvy",["Abnormal irritability; ↓ appetite","Tall stature","Anasarca","Moon face"],0,"Early features: Abnormal irritability; ↓ appetite (Book p73)"),
    q(77,"PEDS-U144",73,"Anemia in scurvy is because",["Vit C is needed for iron absorption","Chronic blood loss","Megaloblastic changes","Hemolysis"],0,"Anemia: Vit C is needed for iron absorption (Book p73)"),
    q(78,"PEDS-U144",73,"Bleeding manifestations in scurvy",["Characteristic (Gum bleeds, Perifollicular bleeding, Subperiosteal)","Always absent","Only nose bleed","Only bruising"],0,"Bleeding manifestations: Characteristic — Gum bleeds; Perifollicular bleeding + corkscrew hair; Bone: Subperiosteal bleeding (Book p73)"),
    q(79,"PEDS-U144",73,"Characteristic hair finding in scurvy",["Corkscrew hair","Straight hair","Flag sign","Kinky hair"],0,"Perifollicular bleeding + corkscrew hair (Book p73)"),
    q(80,"PEDS-U144",73,"Subperiosteal bleeding in scurvy leads to",["Pain(+) → Pseudo paralysis","Painless swelling","No symptoms","Bone fracture"],0,"Bone: Subperiosteal bleeding → Pain(+) → Pseudo paralysis (Book p73)"),
    q(81,"PEDS-U144",73,"Pseudo paralysis in scurvy — posture",["Child keeps his hips & knees semi-flexed → Frog leg posture","Full extension","Torticollis","Arms raised"],0,"Child keeps his hips & knees semi-flexed → Frog leg posture (Book p73)"),
    q(82,"PEDS-U144",73,"Rosary in scurvy",["Painful; Sharp or angulated","Painless & round","String of beads","Absent"],0,"Rosary: Painful; Sharp or angulated (Book p73)"),
    q(83,"PEDS-U144",73,"Diagnosis of scurvy",["Mainly clinical diagnosis","Only X-ray","Only biopsy","Only blood"],0,"DIAGNOSIS: Mainly clinical diagnosis (Book p73)"),
    q(84,"PEDS-U144",73,"X-ray sign — central area in scurvy",["Trümmerfeld's zone","Frankel's line","Pelken's spur","Ring epiphysis"],0,"Central area: Trümmerfeld's zone (Book p73 image)"),
    q(85,"PEDS-U144",73,"X-ray sign — lateral area in scurvy",["Pelken's spur","Trümmerfeld's zone","White line of Frankel","Cupping"],0,"Lateral area: Pelken's spur (Book p73 image)"),
    q(86,"PEDS-U144",73,"Other X-ray findings in scurvy",["Subperiosteal hemorrhage; Area of rarefaction (poorly formed bony trabeculae); Ring epiphysis; White line of Frankel","Cupping + fraying","Double malleolus","Loss of ZPC"],0,"X-Ray: Subperiosteal hemorrhage; Area of rarefaction (Poorly formed bony trabeculae); Ring epiphysis; White line of Frankel (Book p73 image)"),
    q(87,"PEDS-U144",73,"Treatment of scurvy",["Oral vitamin C: 100-200 mg/day","IV vitamin D","Calcium 50-75 mg/kg","Iron only"],0,"TREATMENT: Oral vitamin C: 100-200 mg/day (Book p73)"),
    q(88,"PEDS-U144",73,"Duration of vitamin C in scurvy",["Until lesion subsides","Exactly 12 weeks","7 days","1 week"],0,"Duration: Until lesion subsides (Book p73)"),
]

RANGES = {138:(1,10),139:(11,18),140:(19,36),141:(37,45),142:(46,55),143:(56,70),144:(71,88)}
UNIT_RANGES = {1:(1,10),2:(11,18),3:(19,36),4:(37,45),5:(46,55),6:(56,70),7:(71,88)}
for u in UNITS:
    s,e = UNIT_RANGES[u["n"]]
    u["qs"] = [f"PEDS-C17-{i:03d}" for i in range(s,e+1)]

pages = [q["page"] for q in QUESTIONS]
assert pages == sorted(pages), f"Pages not sorted {pages[:10]}"
assert len(QUESTIONS)==88
assert len(UNITS)==7
for u in UNITS:
    s,e = UNIT_RANGES[u["n"]]
    assert len(u["qs"])==e-s+1
