CH = 20
UNITS = [
    {"id": "PEDS-U161", "ch": 20, "n": 1, "title": "TORCH — General Aspects (Transmission, Trimester, Manifestations)", "sec": "TORCH Infections · p86", "qs": [], "guide": "TORCH Intrauterine infection transmitted from mother to baby: Toxoplasmosis; Others: Syphilis, Zika virus, Parvo B19 virus; Rubella; Cytomegalovirus (CMV); Herpes simplex. Type of maternal infection 1. Primary (mother infected during pregnancy; m/c transmitted) 2. Secondary/reactivation (Latent infection reactivation; Transmission of syphilis, CMV). Time of gestation 1st trimester m/c (Organ anomalies, ↑ risk congenital anomalies, Highest transmission risk). Common manifestations Antenatal IUGR m/c, IUD, Preterm delivery, Abortions; Postnatal Bone marrow suppression (Anemia, thrombocytopenia), Hepatosplenomegaly, Lymphadenopathy, Jaundice/abnormal LFT (Subclinical)."},
    {"id": "PEDS-U162", "ch": 20, "n": 2, "title": "Congenital Rubella Syndrome (CRS) — Triad, Features, Diagnosis, Management", "sec": "Congenital Rubella Syndrome · p86", "qs": [], "guide": "CRS Severe maturation infection. Clinical Triad Heart defects (PDA, Pulmonary artery stenosis PS, VSD), Sensorineural hearing loss (SNHL) m/c, Cataract. Other features 1. Salt and pepper retinopathy (Black and white spots on retina; m/c ocular finding) 2. Blueberry muffin lesion (Purpuric spots non-blanching dome-shaped papules; severe CRS; dermal erythropoiesis; non-specific). Chronic manifestations 1. Progressive rubella panencephalitis (PRP) school going age, similar to SSPE (measles) poor scholastic performance, seizures, intellectual impairment 2. Adult-onset Diabetes 3. Hypothyroidism. Diagnosis Fetal IgM antibodies against rubella (maternal IgM cannot cross placenta); IgG not used (maternal IgG crosses placenta). Management No treatment (damage permanent); Prevention immunization of parent (during their childhood)."},
    {"id": "PEDS-U163", "ch": 20, "n": 3, "title": "Congenital CMV — Transmission, Triad, Diagnosis, Treatment", "sec": "Congenital CMV · p87", "qs": [], "guide": "Congenital CMV m/c TORCH infection. Transmission rate 3rd trimester (90%) → Organogenesis complete → Asymptomatic; 1st trimester → Organogenesis incomplete → Congenital cytomegalic inclusion disease. Triad Microcephaly, Chorioretinitis, Intracranial calcification (periventricular). Other SNHL (m/c long term sequelae; m/c cause of non-syndromic hearing loss in children), Rash (Petechiae d/t ↓ platelets; Blueberry muffin lesion), Hepatosplenomegaly. Diagnosis PCR (Urine > blood > saliva; Screening; as early as possible); Serology (Low sensitivity) IgM antibodies against CMV. Treatment Ganciclovir IV 6 weeks → Oral 6 months; Goal prevent progression neurological disorders, decrease risk of SNHL in future."},
    {"id": "PEDS-U164", "ch": 20, "n": 4, "title": "Congenital Toxoplasmosis — Triad, Diagnosis, Treatment", "sec": "Congenital Toxoplasmosis · p88", "qs": [], "guide": "Transmission risk highest in 3rd trimester. Triad Hydrocephalus (unique), Chorioretinitis, Intracranial calcification (Diffuse calcification). Other Low IQ, Deafness (SNHL), Some cases A/W microcephaly. Diagnosis Serology IgM/IgA ELISA (more sensitive), Immunosorbent agglutination assay (ISAGA) test; PCR in CSF/tissue sample (if neurological involvement +). Treatment Infected child All cases symptomatic and asymptomatic should be treated: [Pyrimethamine + Sulfadiazine x 1 year] + [Folic acid (To prevent bone marrow suppression cause by Rx)]; Infected mothers Spiramycin ↓ transmission risk."},
    {"id": "PEDS-U165", "ch": 20, "n": 5, "title": "Congenital and Perinatal Varicella", "sec": "Congenital Varicella Syndrome · p89", "qs": [], "guide": "Congenital Varicella Syndrome Intrauterine transmission of herpes zoster; Period of risk 2nd trimester (13-20 weeks of gestation). Clinical 1. Cerebral atrophy 2. Microcephaly 3. Limb hypoplasia 4. Cicatrix (Irregular scarring, resembles burn scar). Perinatal Varicella more common than congenital varicella; Period of highest risk 5 days before to 2 days after delivery; Management immediately after birth Varicella zoster > IV Ig (Prevention); If lesions (+) Acyclovir."},
    {"id": "PEDS-U166", "ch": 20, "n": 6, "title": "Congenital Syphilis — Early and Late Features, Management", "sec": "Congenital Syphilis · p89", "qs": [], "guide": "Unique feature Recurrent Abortion; Period of risk >4 months of gestation (≥ 2nd trimester). Early onset <2 years 1st Rhinitis (Snuffles) 2nd Vesiculobullous rash palms and soles (Pemphigus syphiliticus) 3rd Bone (metaphysis, Osteochondritis, Periostitis) → Bone pain, If severe Pseudo paralysis + Edema of affected limb (Soft tissue shadow on xray). Late onset >2 years 1. Hutchinson's triad (SNHL, Interstitial keratitis, Hutchinson's teeth notching/peg shaped incisors) 2. Mulberry molars (Irregular surface d/t rudimentary cups; usually 1st molar) 3. Deformed nose (Preceded by Saddle Nose deformity; Perforations; bony deformities) 4. Rhagodes (Fissures around mouth/nose) 5. Saber shin (Bowing of tibia) 6. Clutton's joint (B/L knee effusion). Management Diagnosis VDRL (baby and mother) 4 fold ↑ titres diagnostic; Treatment Aqueous crystalline penicillin/Penicillin G > 3rd generation cephalosporin: Ceftriaxone."},
    {"id": "PEDS-U167", "ch": 20, "n": 7, "title": "Congenital Zika Virus Infection", "sec": "Congenital Zika · p90", "qs": [], "guide": "Vector Aedes aegypti mosquito → Infected mother → Baby; Period of risk 1st trimester. 1. Skull manifestations Partial collapse of skull, Internal abnormalities (Overlapping of sutures), Brain damage (Microcephaly, Hypertonia/spasticity, Extrapyramidal chorea/athetosis, D/t basal ganglionic damage, Occipital prominence). 2. Limb manifestations Abnormally curved limbs (d/t multiple contractures); Arthrogryposis multiplex congenita. 3. Eye manifestations Coloboma, Pigmentary retinal mottling, Scar + in macula. 4. Others SNHL."},
    {"id": "PEDS-U168", "ch": 20, "n": 8, "title": "Congenital Parvovirus B19 Infection", "sec": "Congenital Parvovirus B19 · p91", "qs": [], "guide": "Transmitted across all trimesters; most sensitive period of transmission 2nd trimester. Tropism for erythroid lineage (Primarily at the pronormoblast stage). Clinical 1. Severe anemia → High output cardiac failure 2. Direct cytopathic effects on myocardium → Myocarditis; Fetal cardiac arrest → IUD (Intrauterine death) 3. Non immune hydrops fetalis."},
]

def q(num, sec, page, qtext, opts, ans, exp):
    assert len(opts)==4 and 0 <= ans <4
    return {"id": f"PEDS-C20-{num:03d}", "sec": sec, "page": page, "q": qtext, "opts": opts, "ans": ans, "exp": exp}

QUESTIONS = [
    q(1,"PEDS-U161",86,"TORCH infections are",["Intrauterine infections transmitted from the mother to the baby","Postnatal infections","Only viral infections","Vector borne only"],0,"Intrauterine infection transmitted from the mother to the baby (Book p86)"),
    q(2,"PEDS-U161",86,"Components of TORCH in the book",["Toxoplasmosis; Others (Syphilis, Zika, Parvo B19); Rubella; Cytomegalovirus; Herpes simplex","Only rubella","Only syphilis","Only CMV"],0,"TORCH: Toxoplasmosis; Others: Syphilis, Zika virus, Parvo B19 virus; Rubella; Cytomegalovirus (CMV); Herpes simplex (Book p86)"),
    q(3,"PEDS-U161",86,"Primary maternal TORCH infection",["Mother infected during pregnancy; m/c transmitted","Reactivation of latent infection","Only seen in toxoplasma","Not transmitted"],0,"1. Primary: mother infected during pregnancy; m/c transmitted (Book p86)"),
    q(4,"PEDS-U161",86,"Secondary/reactivation TORCH infection",["Latent infection reactivation in mother during pregnancy; Transmission of syphilis, CMV","First infection ever","Only in primigravida","Not transmitted to fetus"],0,"2. Secondary/reactivation: Latent infection reactivation in mother during pregnancy; Transmission of syphilis, CMV (Book p86)"),
    q(5,"PEDS-U161",86,"m/c time of gestation for TORCH",["1st trimester","2nd trimester","3rd trimester","Any trimester equally"],0,"Time of gestation: 1st trimester (m/c) (Book p86)"),
    q(6,"PEDS-U161",86,"1st trimester TORCH infection causes",["Organ anomalies; ↑ risk of congenital anomalies; Highest transmission risk","No anomalies","Only jaundice","Only rash"],0,"1st trimester d/t: Organ anomalies; ↑ risk of congenital anomalies; Highest transmission risk (Book p86)"),
    q(7,"PEDS-U161",86,"m/c antenatal manifestation of TORCH",["IUGR","IUD","Preterm delivery","Abortion"],0,"Antenatal: IUGR: m/c (Book p86)"),
    q(8,"PEDS-U161",86,"Other antenatal manifestations of TORCH",["IUD, Preterm delivery, Abortions","Anemia only","Hypertension","Pre-eclampsia"],0,"Antenatal: IUD; Preterm delivery; Abortions (Book p86)"),
    q(9,"PEDS-U161",86,"Postnatal TORCH — bone marrow suppression causes",["Anemia, thrombocytopenia","Polycythemia","Leukocytosis","No effect"],0,"Postnatal: Suppression of bone marrow: Anemia, thrombocytopenia (Book p86)"),
    q(10,"PEDS-U161",86,"Other postnatal TORCH manifestations",["Hepatosplenomegaly; Lymphadenopathy; Jaundice/abnormal LFT (Subclinical)","Aplastic anemia","Splenitis only","Cardiomegaly"],0,"Postnatal: Hepatosplenomegaly; Lymphadenopathy; Jaundice/abnormal LFT (Subclinical) (Book p86)"),
    q(11,"PEDS-U162",86,"Congenital Rubella Syndrome is described as",["Severe maturation infection (per book)","Mild self-limiting infection","Only a rash illness","Late-onset disease"],0,"CRS: Severe maturation infection (Book p86)"),
    q(12,"PEDS-U162",86,"CRS clinical triad — heart",["Heart defects: Patent ductus arteriosus (PDA), Pulmonary artery stenosis (PS), ventricular septal defect (VSD)","ASD only","Atrial septal defect","Aortic stenosis"],0,"Clinical Triad: Heart defects → Patent ductus arteriosus (PDA) → Pulmonary artery stenosis (PS) → ventricular septal defect (VSD) (Book p86)"),
    q(13,"PEDS-U162",86,"CRS triad — hearing",["Sensorineural hearing loss (SNHL): m/c","Conductive loss","Mixed loss","No hearing loss"],0,"Sensorineural hearing loss (SNHL) (m/c) (Book p86)"),
    q(14,"PEDS-U162",86,"CRS triad — eye",["Cataract","Glaucoma","Coloboma","Nystagmus"],0,"Cataract (Book p86)"),
    q(15,"PEDS-U162",87,"Salt and pepper retinopathy in CRS",["Black and white spots on retina; m/c ocular finding","Red spots","Only hemorrhages","Normal retina"],0,"1. Salt and pepper retinopathy: Black and white spots on retina; m/c ocular finding (Book p87)"),
    q(16,"PEDS-U162",87,"Blueberry muffin lesion is",["Purpuric spots: Non-blanching dome-shaped papules","Vesicular rash","Urticaria","Alopecia"],0,"2. Blueberry muffin lesion: Purpuric spots: Non-blanching dome-shaped papules (Book p87)"),
    q(17,"PEDS-U162",87,"Blueberry muffin lesion in CRS",["Found in severe CRS; Represents dermal erythropoiesis; Non-specific (Also seen in other intrauterine infections)","Mild disease only","Due to allergy","Specific to rubella"],0,"Found in severe CRS; Represents dermal erythropoiesis; Non-specific: Also seen in other intrauterine infections (Book p87)"),
    q(18,"PEDS-U162",87,"m/c chronic manifestation of CRS",["Progressive rubella panencephalitis (PRP)","Arthritis","Cardiomyopathy","Diabetes only"],0,"Chronic manifestations 1. Progressive rubella panencephalitis (PRP) (Book p87)"),
    q(19,"PEDS-U162",87,"PRP time of onset",["School going age","Infancy","Adulthood only","Neonatal period only"],0,"Time of onset: School going age (Book p87)"),
    q(20,"PEDS-U162",87,"PRP features",["Similar to SSPE (measles): Poor scholastic performance, Seizures, Intellectual impairment","Similar to Guillain-Barre","Only aphasia","Only ataxia"],0,"Features: Similar to SSPE (measles) — Poor scholastic performance; Seizures; Intellectual impairment (Book p87)"),
    q(21,"PEDS-U162",87,"Other chronic manifestations of CRS",["Adult-onset Diabetes; Hypothyroidism","Arthritis","Osteoporosis","Cataract only"],0,"2. Adult-onset Diabetes; 3. Hypothyroidism (Book p87)"),
    q(22,"PEDS-U162",87,"Diagnosis of CRS",["Fetal IgM antibodies against rubella (maternal IgM cannot cross placenta)","Maternal IgG only","Blood culture","CSF PCR only"],0,"Diagnosis: Fetal IgM antibodies against rubella (maternal IgM cannot cross placenta) (Book p87)"),
    q(23,"PEDS-U162",87,"Why is IgG not used for CRS diagnosis?",["Maternal IgG can cross the placenta","IgG is not produced","IgG is unreliable","IgG is too expensive"],0,"IgG not used as maternal IgG can cross the placenta (Book p87)"),
    q(24,"PEDS-U162",87,"Management of CRS",["No treatment (Damage permanent)","Antiviral cures it","Surgery","Physiotherapy only"],0,"Management: No treatment: Damage permanent (Book p87)"),
    q(25,"PEDS-U162",87,"Prevention of CRS",["Immunization of parent (During their childhood)","No prevention","Treat mother with antivirals","Delivery by C-section"],0,"Prevention: Immunization of parent (During their childhood) (Book p87)"),
    q(26,"PEDS-U163",87,"m/c TORCH infection",["Congenital CMV","Congenital rubella","Congenital syphilis","Congenital toxoplasmosis"],0,"Congenital CMV: m/c TORCH infection (Book p87)"),
    q(27,"PEDS-U163",87,"CMV transmission in 3rd trimester",["(90%) → Organogenesis complete → Asymptomatic","5% → Symptomatic","No transmission","Fatal always"],0,"Transmission rate: 3rd trimester (90%) → Organogenesis complete → Asymptomatic (Book p87)"),
    q(28,"PEDS-U163",87,"CMV transmission in 1st trimester",["Organogenesis incomplete → Congenital cytomegalic inclusion disease","Asymptomatic","No transmission","Only hepatomegaly"],0,"1st trimester → Organogenesis incomplete → Congenital cytomegalic inclusion disease (Book p87)"),
    q(29,"PEDS-U163",88,"Congenital CMV clinical triad",["Microcephaly, Chorioretinitis, Intracranial calcification","Cataract + PDA","Hydrocephalus + chorioretinitis","Rash + fever"],0,"Triad: Microcephaly, Chorioretinitis, Intracranial calcification (Book p88)"),
    q(30,"PEDS-U163",88,"Intracranial calcification in CMV is",["Periventricular (around ventricles)","Diffuse cortical","Subdural","Only cerebellar"],0,"Periventricular calcification; Ventricles (Book p88 image)"),
    q(31,"PEDS-U163",88,"SNHL in congenital CMV",["m/c long term sequelae; m/c cause of non-syndromic hearing loss in children","Conductive loss","Only transient","Not seen"],0,"SNHL: m/c long term sequelae; m/C cause of non-syndromic hearing loss in children (Book p88)"),
    q(32,"PEDS-U163",88,"Rash in congenital CMV",["Petechiae (D/t ↓ platelets); Blueberry muffin lesion","Vesicles","Urticaria","Erythema multiforme"],0,"Rash: Petechiae (D/t ↓ platelets); Blueberry muffin lesion (Book p88)"),
    q(33,"PEDS-U163",88,"Other feature of congenital CMV",["Hepatosplenomegaly","Cardiomegaly","Goiter","Aplasia cutis"],0,"Hepatosplenomegaly (Book p88)"),
    q(34,"PEDS-U163",88,"Diagnosis of congenital CMV — PCR sample preference",["Urine sample > blood sample > saliva (Screening)","Saliva > blood > urine","Blood only","CSF only"],0,"PCR testing: Urine sample > blood sample > saliva (Screening) (Book p88)"),
    q(35,"PEDS-U163",88,"PCR in congenital CMV should be done",["As early as possible","After 1 year","Only if symptomatic","Never"],0,"Done as early as possible (Book p88)"),
    q(36,"PEDS-U163",88,"Serology in congenital CMV",["Low sensitivity: IgM antibodies against CMV","High sensitivity IgG","Anti-IgA","VDRL"],0,"Serology (Low sensitivity): IgM antibodies against cmv (Book p88)"),
    q(37,"PEDS-U163",88,"Treatment of congenital CMV",["Ganciclovir: IV 6 weeks → Oral 6 months","Acyclovir 1 week","Amantadine","No treatment"],0,"Treatment: Ganciclovir: IV 6 weeks → Oral 6 months (Book p88)"),
    q(38,"PEDS-U163",88,"Goal of ganciclovir in congenital CMV",["To prevent progression of neurological disorders; Decrease risk of SNHL in future","To cure the infection","To prevent hepatomegaly","To improve hearing immediately"],0,"Goal: To prevent progression of neurological disorders; Decrease risk of SNHL in future (Book p88)"),
    q(39,"PEDS-U164",88,"Toxoplasmosis transmission risk is highest in",["3rd trimester","1st trimester","2nd trimester","All trimesters equal"],0,"Transmission risk: highest in 3rd trimester (Book p88)"),
    q(40,"PEDS-U164",88,"Congenital toxoplasmosis triad",["Hydrocephalus (unique), Chorioretinitis, Intracranial calcification","Microcephaly + chorioretinitis","Cataract + PDA","Rash + hepatosplenomegaly"],0,"Triad: Hydrocephalus (unique), Chorioretinitis, Intracranial calcification (Book p88)"),
    q(41,"PEDS-U164",88,"Intracranial calcification in toxoplasmosis is",["Diffuse calcification","Periventricular only","Subdural","Cerebellar only"],0,"Diffuse calcification (Book p88 image)"),
    q(42,"PEDS-U164",88,"Other manifestations of congenital toxoplasmosis",["Low IQ; Deafness (SNHL); Some cases: A/W microcephaly","Hypertrophic cardiomyopathy","Goiter","Marfan habitus"],0,"Other manifestations: Low IQ; Deafness (SNHL); Some cases: A/W microcephaly (Book p88)"),
    q(43,"PEDS-U164",88,"Diagnosis — serology in toxoplasmosis",["IgM/IgA ELISA (more sensitive); Immunosorbent agglutination assay (ISAGA) test","IgG only","VDRL","Tzanck smear"],0,"Serology: IgM/IgA ELISA (more sensitive); Immunosorbent agglutination assay (ISAGA) test (Book p88)"),
    q(44,"PEDS-U164",88,"PCR in toxoplasmosis is done on",["CSF/tissue sample (If neurological involvement +)","Urine only","Saliva","Skin biopsy only"],0,"PCR in CSF/tissue sample (If neurological involvement +) (Book p88)"),
    q(45,"PEDS-U164",88,"Treatment of infected child in congenital toxoplasmosis",["All cases, symptomatic and asymptomatic should be treated","Only symptomatic","Only asymptomatic","No treatment"],0,"Infected child: All cases, symptomatic and asymptomatic should be treated (Book p88)"),
    q(46,"PEDS-U164",88,"Rx for congenital toxoplasmosis",["[Pyrimethamine + Sulfadiazine x 1 year] + [Folic acid (To prevent bone marrow suppression cause by Rx)]","Amoxicillin 5 days","Ganciclovir 6 months","Spiramycin alone"],0,"Rx: [Pyrimethamine + Sulfadiazine x 1 year] + [Folic acid (To prevent bone marrow suppression cause by Rx)] (Book p88)"),
    q(47,"PEDS-U164",89,"Infected mothers in congenital toxoplasmosis",["Spiramycin: ↓ transmission risk","Pyrimethamine + sulfadiazine","Ganciclovir","No treatment"],0,"Infected mothers: Spiramycin: ↓ transmission risk (Book p89)"),
    q(48,"PEDS-U165",89,"Congenital varicella syndrome is",["Intrauterine transmission of herpes zoster","Perinatal transmission only","Postnatal infection","Vector transmitted"],0,"Congenital Varicella Syndrome: Intrauterine transmission of herpes zoster (Book p89)"),
    q(49,"PEDS-U165",89,"Period of risk for congenital varicella",["2nd trimester (13-20 weeks of gestation)","1st trimester","3rd trimester","Any time"],0,"Period of risk: 2nd trimester (13-20 weeks of gestation) (Book p89)"),
    q(50,"PEDS-U165",89,"Clinical features of congenital varicella",["Cerebral atrophy; Microcephaly; Limb hypoplasia; Cicatrix (Irregular scarring, resembles burn scar)","Cataract + PDA","Rash only","Deafness only"],0,"Clinical features: 1. Cerebral atrophy 2. Microcephaly 3. Limb hypoplasia 4. Cicatrix (Irregular scarring, resembles burn scar) (Book p89)"),
    q(51,"PEDS-U165",89,"Perinatal varicella",["More common than congenital varicella","Rarer than congenital","Equal frequency","Does not exist"],0,"PERINATAL VARICELLA: more common than congenital varicella (Book p89)"),
    q(52,"PEDS-U165",89,"Period of highest risk for perinatal varicella",["5 days before to 2 days after delivery","2nd trimester","1st trimester","3 weeks after birth"],0,"Period of highest risk: 5 days before to 2 days after delivery (Book p89)"),
    q(53,"PEDS-U165",89,"Management of perinatal varicella immediately after birth",["Varicella zoster (IG) > IV Ig (Prevention); If lesions (+) Acyclovir","Antibiotics only","Observation only","Surgery"],0,"Management: Immediately after birth → Varicella zoster > IV Ig (Prevention); If lesions(+) → Acyclovir (Book p89)"),
    q(54,"PEDS-U166",89,"Unique feature of congenital syphilis",["Recurrent Abortion","Cataract","Rash","Microcephaly"],0,"Unique feature: Recurrent Abortion (Book p89)"),
    q(55,"PEDS-U166",89,"Period of risk for congenital syphilis",[">4 months of gestation (≥ 2nd trimester)","<4 months","1st trimester only","Any time after 1 month"],0,"Period of risk: >4 months of gestation (≥ 2nd trimester) (Book p89)"),
    q(56,"PEDS-U166",89,"Early congenital syphilis onset",["<2 years",">2 years","Adulthood","After 5 years"],0,"Early onset: <2 years (Book p89)"),
    q(57,"PEDS-U166",89,"1st feature of early congenital syphilis",["Rhinitis: Snuffles","Hepatosplenomegaly","Osteochondritis","Mulberry molars"],0,"1st feature: Rhinitis: Snuffles (Book p89)"),
    q(58,"PEDS-U166",89,"2nd feature of early congenital syphilis",["Vesiculobullous rash seen in palms and soles (Pemphigus syphiliticus)","Maculopapular rash on trunk","Vesicles only on face","Eczema"],0,"2nd feature: Vesiculobullous rash seen in palms and soles — Pemphigus syphiliticus (Book p89 image)"),
    q(59,"PEDS-U166",89,"3rd feature of early congenital syphilis — bone",["Metaphysis, Osteochondritis, Periostitis → Bone pain; If severe Pseudo paralysis + Edema of affected limb","Fractures only","Arthritis of hands","Scoliosis"],0,"3rd feature: Bone → metaphysis, Osteochondritis, Periostitis → Bone pain; If severe → Pseudo paralysis + Edema of affected limb (Book p89)"),
    q(60,"PEDS-U166",89,"X-ray finding in early congenital syphilis bone disease",["Soft tissue shadow on xray","Periventricular calcification","Bone destruction only","Normal X-ray"],0,"Soft tissue shadow on xray (Book p89 image)"),
    q(61,"PEDS-U166",90,"Late congenital syphilis onset",[">2 years","<2 years","Adulthood only","After 10 years"],0,"Late onset: >2 years (Book p90)"),
    q(62,"PEDS-U166",90,"Hutchinson's triad in late congenital syphilis",["SNHL, Interstitial keratitis, Hutchinson's teeth","Cataract, PDA, Deafness","Hydrocephalus, Chorioretinitis, Calcification","Saddle nose, Saber shin, Rhagades"],0,"1. Hutchinson's triad: SNHL, Interstitial keratitis, Hutchinson's teeth (Book p90)"),
    q(63,"PEDS-U166",90,"Hutchinson's teeth appearance",["Notching of incisors/peg shaped incisors","Mulberry molars","Missing teeth","Spoon shaped canines"],0,"Notching of incisors/peg shaped incisors (Book p90 image)"),
    q(64,"PEDS-U166",90,"Mulberry molars",["Irregular surface of molars (D/t presence of rudimentary cups); Usually involves 1st molar","Smooth surface","Only 2nd molars","Only canines"],0,"2. Mulberry molars: Irregular surface of molars (D/t presence of rudimentary cups); Usually involves 1st molar (Book p90)"),
    q(65,"PEDS-U166",90,"Deformed nose in late congenital syphilis",["Preceded by Saddle Nose deformity; Perforations; Caused by bony deformities","Only external nares","No nasal involvement","Only functional issue"],0,"3. Deformed nose: Preceded by Saddle Nose deformity; Perforations; Deformed nose (Caused by bony deformities) (Book p90)"),
    q(66,"PEDS-U166",90,"Rhagodes in late congenital syphilis",["Fissures around mouth/nose","Vesicles on palms","Ulcers on tongue","Nail dystrophy"],0,"4. Rhagodes: Fissures around mouth/nose (Book p90)"),
    q(67,"PEDS-U166",90,"Saber shin",["Bowing of tibia","Bowing of femur","Scoliosis","Knee effusion"],0,"5. Saber shin: Bowing of tibia (Book p90)"),
    q(68,"PEDS-U166",90,"Clutton's joint in late congenital syphilis",["B/L knee effusion","Unilateral ankle effusion","Cervical spine effusion","Wrist effusion"],0,"6. Clutton's joint: B/L knee effusion (Book p90)"),
    q(69,"PEDS-U166",90,"Diagnosis of congenital syphilis",["VDRL (Baby and mother)","Widal test","Tzanck smear","Blood culture"],0,"Management: Diagnosis: VDRL (Baby and mother) (Book p90)"),
    q(70,"PEDS-U166",90,"Diagnostic criterion in congenital syphilis serology",["4 fold ↑ titres: Diagnostic","Any positive VDRL","Single low titre","Negative RPR"],0,"4 fold ↑ intires: Diagnostic (Book p90)"),
    q(71,"PEDS-U166",90,"Treatment of congenital syphilis",["Aqueous crystalline penicillin/Penicillin G > 3rd generation cephalosporin: Ceftriaxone","Amoxicillin 5 days","Spiramycin","Doxycycline"],0,"Treatment: Aqueous crystalline penicillin/Penicillin G > 3rd generation cephalosporin: Ceftriaxone (Book p90)"),
    q(72,"PEDS-U167",90,"Vector of Zika virus",["Aedes aegypti mosquito → Infected mother → Baby","Culex mosquito","Tsetse fly","No vector"],0,"Vector: Aedes aegypti mosquito → Infected mother → Baby (Book p90)"),
    q(73,"PEDS-U167",90,"Period of risk for congenital Zika",["1st trimester","2nd trimester","3rd trimester","Any trimester"],0,"Period of risk: 1st trimester (Book p90)"),
    q(74,"PEDS-U167",90,"Skull manifestations of congenital Zika",["Partial collapse of skull; Internal abnormalities (Eg: Overlapping of sutures)","Normal skull","Macrocephaly only","Craniosynostosis only"],0,"1. Skull manifestations: Partial collapse of skull; Internal abnormalities (Eg: Overlapping of sutures) (Book p90)"),
    q(75,"PEDS-U167",90,"Brain damage in congenital Zika",["Microcephaly; Hypertonia/spasticity; Extrapyramidal manifestations: chorea, athetosis; D/t basal ganglionic damage; Occipital prominence","Normal brain","Only seizures","Only hydrocephalus"],0,"Brain damage: Microcephaly; Hypertonia/spasticity; Extrapyramidal manifestations: chorea, athetosis; D/t basal ganglionic damage; Occipital prominence (Book p90)"),
    q(76,"PEDS-U167",91,"Limb manifestations of congenital Zika",["Abnormally curved limbs (D/t multiple contractures); Arthrogryposis multiplex congenita","Limb hypoplasia only","Polydactyly","Normal limbs"],0,"2. Limb manifestations: Abnormally curved limbs (D/t multiple contractures); Arthrogryposis multiplex congenita (Book p91)"),
    q(77,"PEDS-U167",91,"Eye manifestations of congenital Zika",["Coloboma; Pigmentary retinal mottling; Scar + in macula","Cataract only","Glaucoma","Retinoblastoma"],0,"3. Eye manifestations: Coloboma; Pigmentary retinal mottling; Scar + in macula (Book p91)"),
    q(78,"PEDS-U167",91,"Other manifestation of congenital Zika",["SNHL","Cleft lip","PDA","Aplasia cutis"],0,"4. Others: SNHL (Book p91)"),
    q(79,"PEDS-U168",91,"Congenital parvovirus B19 transmission",["Across all trimesters; most sensitive period of transmission: 2nd trimester","1st trimester only","3rd trimester only","Not transmitted in pregnancy"],0,"Transmitted across all trimesters; most sensitive period of transmission: 2nd trimester (Book p91)"),
    q(80,"PEDS-U168",91,"Tropism of parvovirus B19",["Erythroid lineage: Primarily at the pronormoblast stage","Megakaryocytic lineage","Granulocytic lineage","Neuronal lineage"],0,"Tropism for erythroid lineage: Primarily at the pronormoblast stage (Book p91)"),
    q(81,"PEDS-U168",91,"Main clinical feature of congenital parvovirus B19",["Severe anemia → High output cardiac failure","Polycythemia","Hypercalcemia","Jaundice only"],0,"Clinical Features: 1. Severe anemia → High output cardiac failure (Book p91)"),
    q(82,"PEDS-U168",91,"Direct cytopathic effects of B19 on myocardium cause",["Myocarditis; Fetal cardiac arrest → IUD (Intrauterine death)","Hypertrophic cardiomyopathy","ASD","No cardiac effect"],0,"2. Direct cytopathic effects on myocardium → Myocarditis; Fetal cardiac arrest → IUD (Intrauterine death) (Book p91)"),
    q(83,"PEDS-U168",91,"End result shown in congenital parvovirus B19",["Non immune hydrops fetalis","Immune hydrops","Edema of only one limb","Normal baby"],0,"3. Non immune hydrops fetalis (Book p91)"),
]

RANGES = {161:(1,10),162:(11,25),163:(26,38),164:(39,47),165:(48,53),166:(54,71),167:(72,78),168:(79,83)}
UNIT_RANGES = {1:(1,10),2:(11,25),3:(26,38),4:(39,47),5:(48,53),6:(54,71),7:(72,78),8:(79,83)}
for u in UNITS:
    s,e = UNIT_RANGES[u["n"]]
    u["qs"] = [f"PEDS-C20-{i:03d}" for i in range(s,e+1)]

pages = [q["page"] for q in QUESTIONS]
assert pages == sorted(pages), f"Pages not sorted {pages[:10]}"
assert len(QUESTIONS)==83
assert len(UNITS)==8
for u in UNITS:
    s,e = UNIT_RANGES[u["n"]]
    assert len(u["qs"])==e-s+1
